/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `DFT` operator conversion tests (fixture opsets: 19, 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_19() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        19,
        graph(
            "test_DFT_graph",
            vec![
                f32_input("input", &[1, 2]),
            ],
            vec![
                f32_output("output", &[1, 2]),
            ],
            vec![
                node(
                    "DFT",
                    "test_DFT",
                    &["input"],
                    &["output"],
                    &[
                        attr_int("onesided", 0),
                        attr_int("axis", 1),
                        attr_int("inverse", 0),
                    ],
                ),
            ],
            vec![
            ],
        ),
    )
}

#[test]
fn convert_op_opset_19() {
    assert_op_matches_ort(build_fixture_opset_19(), ExpectConvertOp::UnsupportedOp, 19);
}

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_DFT_graph",
            vec![
                f32_input("input", &[1, 2]),
            ],
            vec![
                f32_output("output", &[1, 2]),
            ],
            vec![
                node(
                    "DFT",
                    "test_DFT",
                    &["input"],
                    &["output"],
                    &[
                        attr_int("onesided", 0),
                        attr_int("inverse", 0),
                    ],
                ),
            ],
            vec![
            ],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::UnsupportedOp, 26);
}
