/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `HammingWindow` operator conversion tests (fixture opsets: 17).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_17() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        17,
        graph(
            "test_HammingWindow_graph",
            vec![],
            vec![f32_output("output", &[8])],
            vec![node(
                "HammingWindow",
                "test_HammingWindow",
                &["size"],
                &["output"],
                &[],
            )],
            vec![i64_init("size", &[], &[8])],
        ),
    )
}

#[test]
fn convert_op_opset_17() {
    assert_op_matches_ort(build_fixture_opset_17(), ExpectConvertOp::UnsupportedOp, 17);
}
