/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `MelWeightMatrix` operator conversion tests (fixture opsets: 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_MelWeight_matrix_graph",
            vec![],
            vec![f32_output("output", &[8, 9])],
            vec![node(
                "MelWeightMatrix",
                "test",
                &[
                    "num_mel_bins",
                    "dft_length",
                    "sample_rate",
                    "stft_lower_bound",
                    "stft_upper_bound",
                ],
                &["output"],
                &[],
            )],
            vec![
                i64_init("num_mel_bins", &[], &[8]),
                i64_init("dft_length", &[], &[16]),
                i64_init("sample_rate", &[], &[16000]),
                i64_init("stft_lower_bound", &[], &[0]),
                i64_init("stft_upper_bound", &[], &[8000]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::UnsupportedOp, 26);
}
