/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `STFT` operator conversion test (fixture opset 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_STFT_graph",
            vec![
                f32_input("signal", &[8]),
            ],
            vec![
                f32_output("output", &[5, 2, 2]),
            ],
            vec![
                node(
                    "STFT",
                    "test",
                    &["signal", "frame_step", "frame_length"],
                    &["output"],
                    &[],
                ),
            ],
            vec![
                i64_init("frame_step", &[], &[4]),
                i64_init("frame_length", &[], &[4]),
            ],
        ),
    )
}

#[test]
fn opset26() {
    assert_op_matches_ort(build_fixture(), ExpectConvertOp::UnsupportedOp, 18);
}
