/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

pub mod hardmax;
pub mod log_softmax;
pub mod softmax;
