/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Mod` operator conversion tests (fixture opsets: 13, 13, 13).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_13() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        13,
        graph(
            "test_Mod_graph",
            vec![f32_input("A", &[1, 2]), f32_input("B", &[1, 2])],
            vec![f32_output("C", &[1, 2])],
            vec![node(
                "Mod",
                "test_Mod",
                &["A", "B"],
                &["C"],
                &[attr_int("fmod", 1)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_13() {
    assert_op_matches_ort(build_fixture_opset_13(), ExpectConvertOp::Success, 13);
}

fn build_fixture_opset_13_float16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        13,
        graph(
            "test_Mod_graph",
            vec![f16_input("A", &[1, 2]), f16_input("B", &[1, 2])],
            vec![f16_output("C", &[1, 2])],
            vec![node(
                "Mod",
                "test_Mod",
                &["A", "B"],
                &["C"],
                &[attr_int("fmod", 1)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_13_float16() {
    assert_op_matches_ort(
        build_fixture_opset_13_float16(),
        ExpectConvertOp::Success,
        13,
    );
}

fn build_fixture_opset_13_bfloat16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        13,
        graph(
            "test_Mod_graph",
            vec![bf16_input("A", &[1, 2]), bf16_input("B", &[1, 2])],
            vec![bf16_output("C", &[1, 2])],
            vec![node(
                "Mod",
                "test_Mod",
                &["A", "B"],
                &["C"],
                &[attr_int("fmod", 1)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_13_bfloat16() {
    assert_op_matches_ort(
        build_fixture_opset_13_bfloat16(),
        ExpectConvertOp::ConversionError,
        13,
    );
}
