/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Pow` operator conversion tests (fixture opsets: 11, 26, 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_11() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        11,
        graph(
            "test_Pow_graph",
            vec![f32_input("X", &[1, 2]), f32_input("Y", &[1, 2])],
            vec![f32_output("Z", &[1, 2])],
            vec![node("Pow", "test_Pow", &["X", "Y"], &["Z"], &[])],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_11() {
    assert_op_matches_ort(build_fixture_opset_11(), ExpectConvertOp::Success, 11);
}

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_Pow_graph",
            vec![f32_input("X", &[1, 2]), f32_input("Y", &[1, 2])],
            vec![f32_output("Z", &[1, 2])],
            vec![node("Pow", "test_Pow", &["X", "Y"], &["Z"], &[])],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::Success, 26);
}

fn build_fixture_opset_26_float16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_Pow_graph",
            vec![f16_input("X", &[1, 2]), f16_input("Y", &[1, 2])],
            vec![f16_output("Z", &[1, 2])],
            vec![node("Pow", "test_Pow", &["X", "Y"], &["Z"], &[])],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_26_float16() {
    assert_op_matches_ort(
        build_fixture_opset_26_float16(),
        ExpectConvertOp::Success,
        26,
    );
}
