/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Gemm` operator conversion test (fixture opset 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_Gemm_graph",
            vec![
                f32_input("A", &[1, 2]),
                f32_input("B", &[2, 2]),
            ],
            vec![
                f32_output("Y", &[1, 2]),
            ],
            vec![
                node(
                    "Gemm",
                    "test_Gemm",
                    &["A", "B"],
                    &["Y"],
                    &[
                        attr_int("transA", 0),
                        attr_int("transB", 0),
                        attr_float("alpha", 1.0),
                        attr_float("beta", 1.0),
                    ],
                ),
            ],
            vec![
            ],
        ),
    )
}

#[test]
fn opset26() {
    assert_op_matches_ort(build_fixture(), ExpectConvertOp::Success, 18);
}
