/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `MatMulInteger` operator conversion test (fixture opset 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_MatMulInteger_graph",
            vec![
            ],
            vec![
                i32_output("Y", &[1, 1]),
            ],
            vec![
                node(
                    "MatMulInteger",
                    "test",
                    &["A", "B"],
                    &["Y"],
                    &[],
                ),
            ],
            vec![
                u8_init("A", &[1, 2], &[1, 2]),
                u8_init("B", &[2, 1], &[3, 4]),
            ],
        ),
    )
}

#[test]
fn opset26() {
    assert_op_matches_ort(build_fixture(), ExpectConvertOp::UnsupportedOp, 18);
}
