/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `QLinearMatMul` operator conversion tests (fixture opsets: 10, 21).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_10() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        10,
        graph(
            "test_MatMulInteger_graph",
            vec![],
            vec![i32_output("Y", &[1, 1])],
            vec![node("MatMulInteger", "test", &["A", "B"], &["Y"], &[])],
            vec![
                u8_init("A", &[1, 2], &[1, 2]),
                u8_init("B", &[2, 1], &[3, 4]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_10() {
    assert_op_matches_ort(build_fixture_opset_10(), ExpectConvertOp::UnsupportedOp, 10);
}

fn build_fixture_opset_21() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        21,
        graph(
            "test_MatMulInteger_graph",
            vec![],
            vec![i32_output("Y", &[1, 1])],
            vec![node("MatMulInteger", "test", &["A", "B"], &["Y"], &[])],
            vec![
                u8_init("A", &[1, 2], &[1, 2]),
                u8_init("B", &[2, 1], &[3, 4]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_21() {
    assert_op_matches_ort(build_fixture_opset_21(), ExpectConvertOp::UnsupportedOp, 21);
}
