/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `BatchNormalization` operator conversion tests (fixture opsets: 14, 26, 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_14() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        14,
        graph(
            "test_BatchNormalization_graph",
            vec![f32_input("X", &[1, 1, 4, 4])],
            vec![f32_output("Y", &[1, 1, 4, 4])],
            vec![node(
                "BatchNormalization",
                "test_BatchNormalization",
                &["X", "scale", "B", "input_mean", "input_var"],
                &["Y"],
                &[
                    attr_float("epsilon", 9.999999747378752e-06),
                    attr_int("training_mode", 0),
                ],
            )],
            vec![
                f32_init("scale", &[1], &[1.0]),
                f32_init("B", &[1], &[0.0]),
                f32_init("input_mean", &[1], &[0.0]),
                f32_init("input_var", &[1], &[1.0]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_14() {
    assert_op_matches_ort(build_fixture_opset_14(), ExpectConvertOp::Success, 14);
}

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_BatchNormalization_graph",
            vec![f32_input("X", &[1, 1, 4, 4])],
            vec![f32_output("Y", &[1, 1, 4, 4])],
            vec![node(
                "BatchNormalization",
                "test_BatchNormalization",
                &["X", "scale", "B", "input_mean", "input_var"],
                &["Y"],
                &[
                    attr_float("epsilon", 9.999999747378752e-06),
                    attr_int("training_mode", 0),
                ],
            )],
            vec![
                f32_init("scale", &[1], &[1.0]),
                f32_init("B", &[1], &[0.0]),
                f32_init("input_mean", &[1], &[0.0]),
                f32_init("input_var", &[1], &[1.0]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::Success, 26);
}

fn build_fixture_opset_26_float16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_BatchNormalization_graph",
            vec![f16_input("X", &[1, 1, 4, 4])],
            vec![f16_output("Y", &[1, 1, 4, 4])],
            vec![node(
                "BatchNormalization",
                "test_BatchNormalization",
                &["X", "scale", "B", "input_mean", "input_var"],
                &["Y"],
                &[
                    attr_float("epsilon", 9.999999747378752e-06),
                    attr_int("training_mode", 0),
                ],
            )],
            vec![
                f16_init("scale", &[1], &[15360]),
                f16_init("B", &[1], &[0]),
                f16_init("input_mean", &[1], &[0]),
                f16_init("input_var", &[1], &[15360]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_26_float16() {
    assert_op_matches_ort(
        build_fixture_opset_26_float16(),
        ExpectConvertOp::Success,
        26,
    );
}
