/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `GroupNormalization` operator conversion tests (fixture opsets: 21, 21).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_21() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        21,
        graph(
            "test_GroupNormalization_graph",
            vec![
                f32_input("X", &[1, 2]),
                f32_input("scale", &[1, 2]),
                f32_input("bias", &[1, 2]),
            ],
            vec![f32_output("Y", &[1, 2])],
            vec![node(
                "GroupNormalization",
                "test_GroupNormalization",
                &["X", "scale", "bias"],
                &["Y"],
                &[
                    attr_float("epsilon", 9.999999747378752e-06),
                    attr_int("num_groups", 1),
                    attr_int("stash_type", 1),
                ],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_21() {
    assert_op_matches_ort(build_fixture_opset_21(), ExpectConvertOp::Success, 21);
}

fn build_fixture_opset_21_float16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        21,
        graph(
            "test_GroupNormalization_graph",
            vec![
                f16_input("X", &[1, 2]),
                f16_input("scale", &[1, 2]),
                f16_input("bias", &[1, 2]),
            ],
            vec![f16_output("Y", &[1, 2])],
            vec![node(
                "GroupNormalization",
                "test_GroupNormalization",
                &["X", "scale", "bias"],
                &["Y"],
                &[
                    attr_float("epsilon", 9.999999747378752e-06),
                    attr_int("num_groups", 1),
                    attr_int("stash_type", 1),
                ],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_21_float16() {
    assert_op_matches_ort(
        build_fixture_opset_21_float16(),
        ExpectConvertOp::Success,
        21,
    );
}
