/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `InstanceNormalization` operator conversion test (fixture opset 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_InstanceNormalization_graph",
            vec![
                f32_input("input", &[1, 1, 4, 4]),
                f32_input("scale", &[1]),
                f32_input("B", &[1]),
            ],
            vec![
                f32_output("output", &[1, 1, 4, 4]),
            ],
            vec![
                node(
                    "InstanceNormalization",
                    "test_InstanceNormalization",
                    &["input", "scale", "B"],
                    &["output"],
                    &[
                        attr_float("epsilon", 9.999999747378752e-06),
                    ],
                ),
            ],
            vec![
            ],
        ),
    )
}

#[test]
fn opset26() {
    assert_op_matches_ort(build_fixture(), ExpectConvertOp::UnsupportedOp, 18);
}
