/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `LRN` operator conversion tests (fixture opsets: 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_LRN_graph",
            vec![
                f32_input("X", &[1, 1, 4, 4]),
            ],
            vec![
                f32_output("Y", &[1, 1, 4, 4]),
            ],
            vec![
                node(
                    "LRN",
                    "test_LRN",
                    &["X"],
                    &["Y"],
                    &[
                        attr_float("bias", 1.0),
                        attr_int("size", 1),
                        attr_float("alpha", 9.999999747378752e-05),
                        attr_float("beta", 0.75),
                    ],
                ),
            ],
            vec![
            ],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::UnsupportedOp, 26);
}
