/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `RMSNormalization` operator conversion tests (fixture opsets: 23, 23, 23).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_23() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        23,
        graph(
            "test_RMSNormalization_graph",
            vec![f32_input("X", &[1, 2]), f32_input("scale", &[1, 2])],
            vec![f32_output("Y", &[1, 2])],
            vec![node(
                "RMSNormalization",
                "test_RMSNormalization",
                &["X", "scale"],
                &["Y"],
                &[
                    attr_int("axis", -1),
                    attr_float("epsilon", 9.999999747378752e-06),
                    attr_int("stash_type", 1),
                ],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_23() {
    assert_op_matches_ort(build_fixture_opset_23(), ExpectConvertOp::Success, 23);
}

fn build_fixture_opset_23_float16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        23,
        graph(
            "test_RMSNormalization_graph",
            vec![f16_input("X", &[1, 2]), f16_input("scale", &[1, 2])],
            vec![f16_output("Y", &[1, 2])],
            vec![node(
                "RMSNormalization",
                "test_RMSNormalization",
                &["X", "scale"],
                &["Y"],
                &[
                    attr_int("axis", -1),
                    attr_float("epsilon", 9.999999747378752e-06),
                    attr_int("stash_type", 1),
                ],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_23_float16() {
    assert_op_matches_ort(
        build_fixture_opset_23_float16(),
        ExpectConvertOp::Success,
        23,
    );
}

fn build_fixture_opset_23_bfloat16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        23,
        graph(
            "test_RMSNormalization_graph",
            vec![bf16_input("X", &[1, 2]), bf16_input("scale", &[1, 2])],
            vec![bf16_output("Y", &[1, 2])],
            vec![node(
                "RMSNormalization",
                "test_RMSNormalization",
                &["X", "scale"],
                &["Y"],
                &[
                    attr_int("axis", -1),
                    attr_float("epsilon", 9.999999747378752e-06),
                    attr_int("stash_type", 1),
                ],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_23_bfloat16() {
    assert_op_matches_ort(
        build_fixture_opset_23_bfloat16(),
        ExpectConvertOp::ConversionError,
        23,
    );
}
