/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `RMSNormalization` operator conversion tests (fixture opsets: 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_RMSNormalization_graph",
            vec![f32_input("X", &[1, 2]), f32_input("scale", &[1, 2])],
            vec![f32_output("Y", &[1, 2])],
            vec![node(
                "RMSNormalization",
                "test_RMSNormalization",
                &["X", "scale"],
                &["Y"],
                &[
                    attr_int("axis", -1),
                    attr_float("epsilon", 9.999999747378752e-06),
                    attr_int("stash_type", 1),
                ],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::Success, 26);
}
