/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Concat` operator conversion test (fixture opset 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_Concat_graph",
            vec![
                f32_input("in0", &[1, 2]),
                f32_input("in1", &[1, 2]),
            ],
            vec![
                f32_output("concat_result", &[1, 2]),
            ],
            vec![
                node(
                    "Concat",
                    "test_Concat",
                    &["in0", "in1"],
                    &["concat_result"],
                    &[
                        attr_int("axis", 0),
                    ],
                ),
            ],
            vec![
            ],
        ),
    )
}

#[test]
fn opset26() {
    assert_op_matches_ort(build_fixture(), ExpectConvertOp::Success, 18);
}
