/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `DepthToSpace` operator conversion tests (fixture opsets: 10, 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_10() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        10,
        graph(
            "test_DepthToSpace_graph",
            vec![f32_input("input", &[1, 4, 4, 4])],
            vec![f32_output("output", &[1, 4, 4, 4])],
            vec![node(
                "DepthToSpace",
                "test_DepthToSpace",
                &["input"],
                &["output"],
                &[attr_int("blocksize", 2)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_10() {
    assert_op_matches_ort(build_fixture_opset_10(), ExpectConvertOp::UnsupportedOp, 10);
}

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_DepthToSpace_graph",
            vec![f32_input("input", &[1, 4, 4, 4])],
            vec![f32_output("output", &[1, 4, 4, 4])],
            vec![node(
                "DepthToSpace",
                "test_DepthToSpace",
                &["input"],
                &["output"],
                &[attr_int("blocksize", 2), attr_string("mode", "DCR")],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::UnsupportedOp, 26);
}
