/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `GatherND` operator conversion tests (fixture opsets: 11, 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_11() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        11,
        graph(
            "test_GatherND_graph",
            vec![
                f32_input("data", &[1, 2]),
            ],
            vec![
                f32_output("output", &[1, 2]),
            ],
            vec![
                node(
                    "GatherND",
                    "test_GatherND",
                    &["data", "indices"],
                    &["output"],
                    &[],
                ),
            ],
            vec![
                i64_init("indices", &[1, 1], &[0]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_11() {
    assert_op_matches_ort(build_fixture_opset_11(), ExpectConvertOp::UnsupportedOp, 11);
}

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_GatherND_graph",
            vec![
                f32_input("data", &[1, 2]),
            ],
            vec![
                f32_output("output", &[1, 2]),
            ],
            vec![
                node(
                    "GatherND",
                    "test_GatherND",
                    &["data", "indices"],
                    &["output"],
                    &[
                        attr_int("batch_dims", 0),
                    ],
                ),
            ],
            vec![
                i64_init("indices", &[1, 1], &[0]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::UnsupportedOp, 26);
}
