/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Reshape` operator conversion test (fixture opset 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_Reshape_graph",
            vec![
                f32_input("data", &[1, 2]),
            ],
            vec![
                f32_output("reshaped", &[1, 2]),
            ],
            vec![
                node(
                    "Reshape",
                    "test_Reshape",
                    &["data", "shape"],
                    &["reshaped"],
                    &[
                        attr_int("allowzero", 0),
                    ],
                ),
            ],
            vec![
                i64_init("shape", &[2], &[1, 2]),
            ],
        ),
    )
}

#[test]
fn opset26() {
    assert_op_matches_ort(build_fixture(), ExpectConvertOp::Success, 18);
}
