/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `ReverseSequence` operator conversion tests (fixture opsets: 10, 10).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_10() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        10,
        graph(
            "test_ReverseSequence_graph",
            vec![f32_input("input", &[3, 2, 4])],
            vec![f32_output("Y", &[3, 2, 4])],
            vec![node(
                "ReverseSequence",
                "test",
                &["input", "sequence_lens"],
                &["Y"],
                &[attr_int("batch_axis", 0), attr_int("time_axis", 1)],
            )],
            vec![i64_init("sequence_lens", &[3], &[2, 2, 2])],
        ),
    )
}

#[test]
fn convert_op_opset_10() {
    assert_op_matches_ort(build_fixture_opset_10(), ExpectConvertOp::Success, 10);
}

fn build_fixture_opset_10_float16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        10,
        graph(
            "test_ReverseSequence_graph",
            vec![f16_input("input", &[3, 2, 4])],
            vec![f16_output("Y", &[3, 2, 4])],
            vec![node(
                "ReverseSequence",
                "test",
                &["input", "sequence_lens"],
                &["Y"],
                &[attr_int("batch_axis", 0), attr_int("time_axis", 1)],
            )],
            vec![i64_init("sequence_lens", &[3], &[2, 2, 2])],
        ),
    )
}

#[test]
fn convert_op_opset_10_float16() {
    assert_op_matches_ort(
        build_fixture_opset_10_float16(),
        ExpectConvertOp::Success,
        10,
    );
}
