/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `ReverseSequence` operator conversion tests (fixture opsets: 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_ReverseSequence_graph",
            vec![
                f32_input("input", &[3, 2, 4]),
            ],
            vec![
                f32_output("Y", &[3, 2, 4]),
            ],
            vec![
                node(
                    "ReverseSequence",
                    "test",
                    &["input", "sequence_lens"],
                    &["Y"],
                    &[
                        attr_int("batch_axis", 0),
                        attr_int("time_axis", 1),
                    ],
                ),
            ],
            vec![
                i64_init("sequence_lens", &[3], &[2, 2, 2]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::UnsupportedOp, 26);
}
