/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `SpaceToDepth` operator conversion test (fixture opset 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_SpaceToDepth_graph",
            vec![
                f32_input("input", &[1, 4, 4, 4]),
            ],
            vec![
                f32_output("output", &[1, 4, 4, 4]),
            ],
            vec![
                node(
                    "SpaceToDepth",
                    "test_SpaceToDepth",
                    &["input"],
                    &["output"],
                    &[
                        attr_int("blocksize", 2),
                    ],
                ),
            ],
            vec![
            ],
        ),
    )
}

#[test]
fn opset26() {
    assert_op_matches_ort(build_fixture(), ExpectConvertOp::UnsupportedOp, 18);
}
