/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Split` operator conversion tests (fixture opsets: 11, 18, 18).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_11() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        11,
        graph(
            "test_Split_graph",
            vec![f32_input("input", &[1, 2])],
            vec![f32_output("out0", &[1, 1]), f32_output("out1", &[1, 1])],
            vec![node(
                "Split",
                "test",
                &["input"],
                &["out0", "out1"],
                &[attr_int("axis", 1), attr_ints("split", &[1, 1])],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_11() {
    assert_op_matches_ort(build_fixture_opset_11(), ExpectConvertOp::Success, 11);
}

fn build_fixture_opset_18() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        18,
        graph(
            "test_Split_graph",
            vec![f32_input("input", &[1, 2])],
            vec![f32_output("out0", &[1, 1]), f32_output("out1", &[1, 1])],
            vec![node(
                "Split",
                "test",
                &["input"],
                &["out0", "out1"],
                &[attr_int("axis", 1), attr_int("num_outputs", 2)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_18() {
    assert_op_matches_ort(build_fixture_opset_18(), ExpectConvertOp::Success, 18);
}

fn build_fixture_opset_18_float16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        18,
        graph(
            "test_Split_graph",
            vec![f16_input("input", &[1, 2])],
            vec![f16_output("out0", &[1, 1]), f16_output("out1", &[1, 1])],
            vec![node(
                "Split",
                "test",
                &["input"],
                &["out0", "out1"],
                &[attr_int("axis", 1), attr_int("num_outputs", 2)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_18_float16() {
    assert_op_matches_ort(
        build_fixture_opset_18_float16(),
        ExpectConvertOp::Success,
        18,
    );
}
