/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Split` operator conversion test (fixture opset 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_Split_graph",
            vec![
                f32_input("input", &[1, 2]),
            ],
            vec![
                f32_output("out0", &[1]),
                f32_output("out1", &[1]),
            ],
            vec![
                node(
                    "Split",
                    "test",
                    &["input"],
                    &["out0", "out1"],
                    &[
                        attr_int("axis", 0),
                        attr_int("num_outputs", 2),
                    ],
                ),
            ],
            vec![
            ],
        ),
    )
}

#[test]
fn opset26() {
    assert_op_matches_ort(build_fixture(), ExpectConvertOp::Success, 18);
}
