/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Squeeze` operator conversion tests (fixture opsets: 11, 25, 25, 13).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_11() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        11,
        graph(
            "test_Squeeze_graph",
            vec![f32_input("data", &[1, 2])],
            vec![f32_output("squeezed", &[2])],
            vec![node(
                "Squeeze",
                "test_Squeeze",
                &["data"],
                &["squeezed"],
                &[],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_11() {
    assert_op_matches_ort(build_fixture_opset_11(), ExpectConvertOp::Success, 11);
}

fn build_fixture_opset_25() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        25,
        graph(
            "test_Squeeze_graph",
            vec![f32_input("data", &[1, 2])],
            vec![f32_output("squeezed", &[2])],
            vec![node(
                "Squeeze",
                "test_Squeeze",
                &["data"],
                &["squeezed"],
                &[],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_25() {
    assert_op_matches_ort(build_fixture_opset_25(), ExpectConvertOp::Success, 25);
}

fn build_fixture_opset_25_float16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        25,
        graph(
            "test_Squeeze_graph",
            vec![f16_input("data", &[1, 2])],
            vec![f16_output("squeezed", &[2])],
            vec![node(
                "Squeeze",
                "test_Squeeze",
                &["data"],
                &["squeezed"],
                &[],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_25_float16() {
    assert_op_matches_ort(
        build_fixture_opset_25_float16(),
        ExpectConvertOp::Success,
        25,
    );
}

fn build_fixture_opset_13_bfloat16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        13,
        graph(
            "test_Squeeze_graph",
            vec![bf16_input("data", &[1, 2])],
            vec![bf16_output("squeezed", &[2])],
            vec![node(
                "Squeeze",
                "test_Squeeze",
                &["data"],
                &["squeezed"],
                &[],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_13_bfloat16() {
    assert_op_matches_ort(
        build_fixture_opset_13_bfloat16(),
        ExpectConvertOp::ConversionError,
        13,
    );
}
