/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Unsqueeze` operator conversion tests (fixture opsets: 11, 25, 25, 13).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_11() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        11,
        graph(
            "test_Unsqueeze_graph",
            vec![f32_input("data", &[1, 2])],
            vec![f32_output("expanded", &[1, 1, 2])],
            vec![node(
                "Unsqueeze",
                "test_Unsqueeze",
                &["data"],
                &["expanded"],
                &[attr_ints("axes", &[0])],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_11() {
    assert_op_matches_ort(build_fixture_opset_11(), ExpectConvertOp::Success, 11);
}

fn build_fixture_opset_25() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        25,
        graph(
            "test_Unsqueeze_graph",
            vec![f32_input("data", &[1, 2])],
            vec![f32_output("expanded", &[1, 1, 2])],
            vec![node(
                "Unsqueeze",
                "test_Unsqueeze",
                &["data", "axes"],
                &["expanded"],
                &[],
            )],
            vec![i64_init("axes", &[1], &[0])],
        ),
    )
}

#[test]
fn convert_op_opset_25() {
    assert_op_matches_ort(build_fixture_opset_25(), ExpectConvertOp::Success, 25);
}

fn build_fixture_opset_25_float16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        25,
        graph(
            "test_Unsqueeze_graph",
            vec![f16_input("data", &[1, 2])],
            vec![f16_output("expanded", &[1, 1, 2])],
            vec![node(
                "Unsqueeze",
                "test_Unsqueeze",
                &["data", "axes"],
                &["expanded"],
                &[],
            )],
            vec![i64_init("axes", &[1], &[0])],
        ),
    )
}

#[test]
fn convert_op_opset_25_float16() {
    assert_op_matches_ort(
        build_fixture_opset_25_float16(),
        ExpectConvertOp::Success,
        25,
    );
}

fn build_fixture_opset_13_bfloat16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        13,
        graph(
            "test_Unsqueeze_graph",
            vec![bf16_input("data", &[1, 2])],
            vec![bf16_output("expanded", &[1, 1, 2])],
            vec![node(
                "Unsqueeze",
                "test_Unsqueeze",
                &["data", "axes"],
                &["expanded"],
                &[],
            )],
            vec![i64_init("axes", &[1], &[0])],
        ),
    )
}

#[test]
fn convert_op_opset_13_bfloat16() {
    assert_op_matches_ort(
        build_fixture_opset_13_bfloat16(),
        ExpectConvertOp::ConversionError,
        13,
    );
}
