/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `ConcatFromSequence` operator conversion test (fixture opset 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

// Fixture builder failed at codegen: Node(test) with schema(::ConcatFromSequence:11) has input size 2 not in range [min=1, max=1]. ==> Context: Bad node spec for node. Name: test OpType: ConcatFromSequence
#[test]
#[ignore = "fixture builder failed at codegen: Node test with schema ::ConcatFromSequence:11 has input size 2 not in range min 1 max 1 . Context: Bad node spec for nod"]
fn opset26() {}
