/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `SequenceErase` operator conversion tests (fixture opsets: 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_SequenceErase_graph",
            vec![],
            vec![sequence_f32_output("output_sequence", &[1, 2])],
            vec![
                node("SequenceConstruct", "mk", &["t0"], &["seq"], &[]),
                node(
                    "SequenceErase",
                    "test",
                    &["seq", "position"],
                    &["output_sequence"],
                    &[],
                ),
            ],
            vec![
                f32_init("t0", &[1, 2], &[0.0, 0.0]),
                i64_init("position", &[], &[0]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::UnsupportedOp, 26);
}
