/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `SequenceConstruct` operator conversion tests (fixture opsets: 11).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_11() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        11,
        graph(
            "test_SequenceConstruct_graph",
            vec![],
            vec![sequence_f32_output("output_sequence", &[1, 2])],
            vec![node(
                "SequenceConstruct",
                "test",
                &["t0"],
                &["output_sequence"],
                &[],
            )],
            vec![f32_init("t0", &[1, 2], &[0.0, 0.0])],
        ),
    )
}

#[test]
fn convert_op_opset_11() {
    assert_op_matches_ort(build_fixture_opset_11(), ExpectConvertOp::UnsupportedOp, 11);
}
