/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `SequenceMap` operator conversion test (fixture opset 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_SequenceMap_graph",
            vec![
            ],
            vec![
                sequence_f32_output("out_sequence", &[1, 2]),
            ],
            vec![
                node(
                    "SequenceConstruct",
                    "make_seq",
                    &["t0"],
                    &["input_sequence"],
                    &[],
                ),
                node(
                    "SequenceMap",
                    "test_SequenceMap",
                    &["input_sequence"],
                    &["out_sequence"],
                    &[
                        attr_graph("body", graph(
                                "body",
                                vec![
                                    f32_input("current", &[1, 2]),
                                ],
                                vec![
                                    f32_output("out", &[1, 2]),
                                ],
                                vec![
                                    node(
                                        "Identity",
                                        "id_elem",
                                        &["current"],
                                        &["out"],
                                        &[],
                                    ),
                                ],
                                vec![
                                ],
                            )),
                    ],
                ),
            ],
            vec![
                f32_init("t0", &[1, 2], &[0.0, 0.0]),
            ],
        ),
    )
}

#[test]
fn opset26() {
    assert_op_matches_ort(build_fixture(), ExpectConvertOp::UnsupportedOp, 18);
}
