/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `GRU` operator conversion tests (fixture opsets: 9, 22, 22, 22).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_9() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        9,
        graph(
            "test_GRU_graph",
            vec![
                f32_input("X", &[1, 3, 4]),
                f32_input("W", &[1, 12, 4]),
                f32_input("R", &[1, 12, 4]),
                f32_input("B", &[1, 24]),
            ],
            vec![f32_output("Y", &[1, 1, 4])],
            vec![node(
                "GRU",
                "test_GRU",
                &["X", "W", "R", "B"],
                &["Y"],
                &[attr_int("hidden_size", 4)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_9() {
    assert_op_matches_ort(build_fixture_opset_9(), ExpectConvertOp::Success, 9);
}

fn build_fixture_opset_22() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        22,
        graph(
            "test_GRU_graph",
            vec![
                f32_input("X", &[1, 3, 4]),
                f32_input("W", &[1, 12, 4]),
                f32_input("R", &[1, 12, 4]),
                f32_input("B", &[1, 24]),
            ],
            vec![f32_output("Y", &[1, 1, 4])],
            vec![node(
                "GRU",
                "test_GRU",
                &["X", "W", "R", "B"],
                &["Y"],
                &[attr_int("hidden_size", 4)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_22() {
    assert_op_matches_ort(build_fixture_opset_22(), ExpectConvertOp::Success, 22);
}

fn build_fixture_opset_22_float16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        22,
        graph(
            "test_GRU_graph",
            vec![
                f16_input("X", &[1, 3, 4]),
                f16_input("W", &[1, 12, 4]),
                f16_input("R", &[1, 12, 4]),
                f16_input("B", &[1, 24]),
            ],
            vec![f16_output("Y", &[1, 1, 4])],
            vec![node(
                "GRU",
                "test_GRU",
                &["X", "W", "R", "B"],
                &["Y"],
                &[attr_int("hidden_size", 4)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_22_float16() {
    assert_op_matches_ort(
        build_fixture_opset_22_float16(),
        ExpectConvertOp::Success,
        22,
    );
}

fn build_fixture_opset_22_bfloat16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        22,
        graph(
            "test_GRU_graph",
            vec![
                bf16_input("X", &[1, 3, 4]),
                bf16_input("W", &[1, 12, 4]),
                bf16_input("R", &[1, 12, 4]),
                bf16_input("B", &[1, 24]),
            ],
            vec![bf16_output("Y", &[1, 1, 4])],
            vec![node(
                "GRU",
                "test_GRU",
                &["X", "W", "R", "B"],
                &["Y"],
                &[attr_int("hidden_size", 4)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_22_bfloat16() {
    assert_op_matches_ort(
        build_fixture_opset_22_bfloat16(),
        ExpectConvertOp::ConversionError,
        22,
    );
}
