/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `GRU` operator conversion test (fixture opset 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_GRU_graph",
            vec![
                f32_input("X", &[1, 3, 4]),
                f32_input("W", &[1, 12, 4]),
                f32_input("R", &[1, 12, 4]),
                f32_input("B", &[1, 24]),
            ],
            vec![
                f32_output("Y", &[1, 1, 4]),
            ],
            vec![
                node(
                    "GRU",
                    "test_GRU",
                    &["X", "W", "R", "B"],
                    &["Y"],
                    &[
                        attr_int("hidden_size", 4),
                    ],
                ),
            ],
            vec![
            ],
        ),
    )
}

#[test]
fn opset26() {
    assert_op_matches_ort(build_fixture(), ExpectConvertOp::UnsupportedOp, 18);
}
