/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `LSTM` operator conversion tests (fixture opsets: 13, 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_13() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        13,
        graph(
            "test_LSTM_graph",
            vec![
                f32_input("X", &[1, 3, 4]),
                f32_input("W", &[1, 16, 4]),
                f32_input("R", &[1, 16, 4]),
                f32_input("B", &[1, 32]),
            ],
            vec![f32_output("Y", &[1, 1, 4])],
            vec![node(
                "LSTM",
                "test_LSTM",
                &["X", "W", "R", "B"],
                &["Y"],
                &[attr_int("hidden_size", 4)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_13() {
    assert_op_matches_ort(build_fixture_opset_13(), ExpectConvertOp::Success, 13);
}

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_LSTM_graph",
            vec![
                f32_input("X", &[1, 3, 4]),
                f32_input("W", &[1, 16, 4]),
                f32_input("R", &[1, 16, 4]),
                f32_input("B", &[1, 32]),
            ],
            vec![f32_output("Y", &[1, 1, 4])],
            vec![node(
                "LSTM",
                "test_LSTM",
                &["X", "W", "R", "B"],
                &["Y"],
                &[attr_int("hidden_size", 4)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::Success, 26);
}
