/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `RotaryEmbedding` operator conversion test (fixture opset 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

// Fixture builder failed at codegen: Node(test) with schema(::RotaryEmbedding:23) has input size 2 not in range [min=3, max=4]. ==> Context: Bad node spec for node. Name: test OpType: RotaryEmbedding
#[test]
#[ignore = "fixture builder failed at codegen: Node test with schema ::RotaryEmbedding:23 has input size 2 not in range min 3 max 4 . Context: Bad node spec for node. "]
fn opset26() {}
