/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `RotaryEmbedding` operator conversion tests (fixture opsets: 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_RotaryEmbedding_graph",
            vec![f32_input("x", &[1, 4, 2, 2])],
            vec![f32_output("out", &[1, 4, 2, 2])],
            vec![node(
                "RotaryEmbedding",
                "test",
                &["x", "cos_cache", "sin_cache"],
                &["out"],
                &[
                    attr_int("num_heads", 4),
                    attr_int("rotary_embedding_dim", 2),
                ],
            )],
            vec![
                f32_init("cos_cache", &[1, 2, 1], &[1.0, 1.0]),
                f32_init("sin_cache", &[1, 2, 1], &[0.0, 0.0]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::UnsupportedOp, 26);
}
