/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `CumProd` operator conversion test (fixture opset 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_CumProd_graph",
            vec![
                f32_input("x", &[1, 2]),
            ],
            vec![
                f32_output("y", &[1, 2]),
            ],
            vec![
                node(
                    "CumProd",
                    "test_CumProd",
                    &["x", "axis"],
                    &["y"],
                    &[],
                ),
            ],
            vec![
                i64_init("axis", &[], &[0]),
            ],
        ),
    )
}

#[test]
fn opset26() {
    assert_op_matches_ort(build_fixture(), ExpectConvertOp::UnsupportedOp, 18);
}
