/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `NonMaxSuppression` operator conversion test (fixture opset 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_NonMaxSuppression_graph",
            vec![
                f32_input("boxes", &[1, 4, 4]),
                f32_input("scores", &[1, 1, 4]),
            ],
            vec![
                i64_output("selected_indices", &[0, 3]),
            ],
            vec![
                node(
                    "NonMaxSuppression",
                    "test",
                    &["boxes", "scores"],
                    &["selected_indices"],
                    &[],
                ),
            ],
            vec![
            ],
        ),
    )
}

#[test]
fn opset26() {
    assert_op_matches_ort(build_fixture(), ExpectConvertOp::UnsupportedOp, 18);
}
