/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Scatter` operator conversion tests (fixture opsets: 9).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_9() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        9,
        graph(
            "test_Scatter_graph",
            vec![f32_input("data", &[1, 2]), f32_input("updates", &[1, 2])],
            vec![f32_output("output", &[1, 2])],
            vec![node(
                "Scatter",
                "test_Scatter",
                &["data", "indices", "updates"],
                &["output"],
                &[attr_int("axis", 0)],
            )],
            vec![i64_init("indices", &[1, 2], &[0, 0])],
        ),
    )
}

#[test]
fn convert_op_opset_9() {
    assert_op_matches_ort(build_fixture_opset_9(), ExpectConvertOp::UnsupportedOp, 9);
}
