/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `DequantizeLinear` operator conversion tests (fixture opsets: 10, 13, 19, 21, 25, 25).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_10() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        10,
        graph(
            "test_DequantizeLinear_graph",
            vec![],
            vec![f32_output("y", &[1, 2])],
            vec![node(
                "DequantizeLinear",
                "test",
                &["x", "x_scale", "x_zero_point"],
                &["y"],
                &[],
            )],
            vec![
                u8_init("x", &[2], &[1, 2]),
                f32_init("x_scale", &[], &[0.5]),
                u8_init("x_zero_point", &[], &[0]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_10() {
    assert_op_matches_ort(build_fixture_opset_10(), ExpectConvertOp::Success, 10);
}

fn build_fixture_opset_13() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        13,
        graph(
            "test_DequantizeLinear_graph",
            vec![],
            vec![f32_output("y", &[1, 2])],
            vec![node(
                "DequantizeLinear",
                "test",
                &["x", "x_scale", "x_zero_point"],
                &["y"],
                &[],
            )],
            vec![
                u8_init("x", &[2], &[1, 2]),
                f32_init("x_scale", &[], &[0.5]),
                u8_init("x_zero_point", &[], &[0]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_13() {
    assert_op_matches_ort(build_fixture_opset_13(), ExpectConvertOp::Success, 13);
}

fn build_fixture_opset_19() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        19,
        graph(
            "test_DequantizeLinear_graph",
            vec![],
            vec![f32_output("y", &[1, 2])],
            vec![node(
                "DequantizeLinear",
                "test",
                &["x", "x_scale", "x_zero_point"],
                &["y"],
                &[],
            )],
            vec![
                u8_init("x", &[2], &[1, 2]),
                f32_init("x_scale", &[], &[0.5]),
                u8_init("x_zero_point", &[], &[0]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_19() {
    assert_op_matches_ort(build_fixture_opset_19(), ExpectConvertOp::Success, 19);
}

fn build_fixture_opset_21() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        21,
        graph(
            "test_DequantizeLinear_graph",
            vec![],
            vec![f32_output("y", &[1, 2])],
            vec![node(
                "DequantizeLinear",
                "test",
                &["x", "x_scale", "x_zero_point"],
                &["y"],
                &[],
            )],
            vec![
                u8_init("x", &[2], &[1, 2]),
                f32_init("x_scale", &[], &[0.5]),
                u8_init("x_zero_point", &[], &[0]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_21() {
    assert_op_matches_ort(build_fixture_opset_21(), ExpectConvertOp::Success, 21);
}

fn build_fixture_opset_25() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        25,
        graph(
            "test_DequantizeLinear_graph",
            vec![],
            vec![f32_output("y", &[1, 2])],
            vec![node(
                "DequantizeLinear",
                "test",
                &["x", "x_scale", "x_zero_point"],
                &["y"],
                &[],
            )],
            vec![
                u8_init("x", &[2], &[1, 2]),
                f32_init("x_scale", &[], &[0.5]),
                u8_init("x_zero_point", &[], &[0]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_25() {
    assert_op_matches_ort(build_fixture_opset_25(), ExpectConvertOp::Success, 25);
}

fn build_fixture_opset_25_float16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        25,
        graph(
            "test_DequantizeLinear_graph",
            vec![],
            vec![f16_output("y", &[1, 2])],
            vec![node(
                "DequantizeLinear",
                "test",
                &["x", "x_scale", "x_zero_point"],
                &["y"],
                &[],
            )],
            vec![
                u8_init("x", &[2], &[1, 2]),
                f16_init("x_scale", &[], &[14336]),
                u8_init("x_zero_point", &[], &[0]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_25_float16() {
    assert_op_matches_ort(
        build_fixture_opset_25_float16(),
        ExpectConvertOp::Success,
        25,
    );
}
