/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `DynamicQuantizeLinear` operator conversion tests (fixture opsets: 11).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_11() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        11,
        graph(
            "test_DynamicQuantizeLinear_graph",
            vec![f32_input("x", &[1, 2])],
            vec![
                u8_output("y", &[1, 2]),
                f32_output("y_scale", &[]),
                u8_output("y_zero_point", &[]),
            ],
            vec![node(
                "DynamicQuantizeLinear",
                "test",
                &["x"],
                &["y", "y_scale", "y_zero_point"],
                &[],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_11() {
    assert_op_matches_ort(build_fixture_opset_11(), ExpectConvertOp::Success, 11);
}
