/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `QuantizeLinear` operator conversion tests (fixture opsets: 12, 18, 20, 22, 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_12() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        12,
        graph(
            "test_QuantizeLinear_graph",
            vec![f32_input("x", &[1, 2])],
            vec![u8_output("y", &[1, 2])],
            vec![node(
                "QuantizeLinear",
                "test",
                &["x", "y_scale", "y_zero_point"],
                &["y"],
                &[],
            )],
            vec![
                f32_init("y_scale", &[], &[0.5]),
                u8_init("y_zero_point", &[], &[0]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_12() {
    assert_op_matches_ort(build_fixture_opset_12(), ExpectConvertOp::UnsupportedOp, 12);
}

fn build_fixture_opset_18() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        18,
        graph(
            "test_QuantizeLinear_graph",
            vec![f32_input("x", &[1, 2])],
            vec![u8_output("y", &[1, 2])],
            vec![node(
                "QuantizeLinear",
                "test",
                &["x", "y_scale", "y_zero_point"],
                &["y"],
                &[],
            )],
            vec![
                f32_init("y_scale", &[], &[0.5]),
                u8_init("y_zero_point", &[], &[0]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_18() {
    assert_op_matches_ort(build_fixture_opset_18(), ExpectConvertOp::UnsupportedOp, 18);
}

fn build_fixture_opset_20() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        20,
        graph(
            "test_QuantizeLinear_graph",
            vec![f32_input("x", &[1, 2])],
            vec![u8_output("y", &[1, 2])],
            vec![node(
                "QuantizeLinear",
                "test",
                &["x", "y_scale", "y_zero_point"],
                &["y"],
                &[],
            )],
            vec![
                f32_init("y_scale", &[], &[0.5]),
                u8_init("y_zero_point", &[], &[0]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_20() {
    assert_op_matches_ort(build_fixture_opset_20(), ExpectConvertOp::UnsupportedOp, 20);
}

fn build_fixture_opset_22() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        22,
        graph(
            "test_QuantizeLinear_graph",
            vec![f32_input("x", &[1, 2])],
            vec![u8_output("y", &[1, 2])],
            vec![node(
                "QuantizeLinear",
                "test",
                &["x", "y_scale", "y_zero_point"],
                &["y"],
                &[],
            )],
            vec![
                f32_init("y_scale", &[], &[0.5]),
                u8_init("y_zero_point", &[], &[0]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_22() {
    assert_op_matches_ort(build_fixture_opset_22(), ExpectConvertOp::UnsupportedOp, 22);
}

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_QuantizeLinear_graph",
            vec![f32_input("x", &[1, 2])],
            vec![u8_output("y", &[1, 2])],
            vec![node(
                "QuantizeLinear",
                "test",
                &["x", "y_scale", "y_zero_point"],
                &["y"],
                &[],
            )],
            vec![
                f32_init("y_scale", &[], &[0.5]),
                u8_init("y_zero_point", &[], &[0]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::UnsupportedOp, 26);
}
