/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `ArgMin` operator conversion test (fixture opset 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_ArgMin_graph",
            vec![
                f32_input("data", &[1, 2]),
            ],
            vec![
                i64_output("reduced", &[2]),
            ],
            vec![
                node(
                    "ArgMin",
                    "test_ArgMin",
                    &["data"],
                    &["reduced"],
                    &[
                        attr_int("axis", 0),
                        attr_int("keepdims", 1),
                        attr_int("select_last_index", 0),
                    ],
                ),
            ],
            vec![
            ],
        ),
    )
}

#[test]
fn opset26() {
    assert_op_matches_ort(build_fixture(), ExpectConvertOp::UnsupportedOp, 18);
}
