/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `ArgMin` operator conversion tests (fixture opsets: 11, 13, 13, 13).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_11() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        11,
        graph(
            "test_ArgMin_graph",
            vec![f32_input("data", &[1, 2])],
            vec![i64_output("reduced", &[2])],
            vec![node(
                "ArgMin",
                "test_ArgMin",
                &["data"],
                &["reduced"],
                &[attr_int("axis", 0), attr_int("keepdims", 1)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_11() {
    assert_op_matches_ort(build_fixture_opset_11(), ExpectConvertOp::Success, 11);
}

fn build_fixture_opset_13() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        13,
        graph(
            "test_ArgMin_graph",
            vec![f32_input("data", &[1, 2])],
            vec![i64_output("reduced", &[2])],
            vec![node(
                "ArgMin",
                "test_ArgMin",
                &["data"],
                &["reduced"],
                &[
                    attr_int("axis", 0),
                    attr_int("keepdims", 1),
                    attr_int("select_last_index", 0),
                ],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_13() {
    assert_op_matches_ort(build_fixture_opset_13(), ExpectConvertOp::Success, 13);
}

fn build_fixture_opset_13_float16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        13,
        graph(
            "test_ArgMin_graph",
            vec![f16_input("data", &[1, 2])],
            vec![i64_output("reduced", &[2])],
            vec![node(
                "ArgMin",
                "test_ArgMin",
                &["data"],
                &["reduced"],
                &[
                    attr_int("axis", 0),
                    attr_int("keepdims", 1),
                    attr_int("select_last_index", 0),
                ],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_13_float16() {
    assert_op_matches_ort(
        build_fixture_opset_13_float16(),
        ExpectConvertOp::Success,
        13,
    );
}

fn build_fixture_opset_13_bfloat16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        13,
        graph(
            "test_ArgMin_graph",
            vec![bf16_input("data", &[1, 2])],
            vec![i64_output("reduced", &[2])],
            vec![node(
                "ArgMin",
                "test_ArgMin",
                &["data"],
                &["reduced"],
                &[
                    attr_int("axis", 0),
                    attr_int("keepdims", 1),
                    attr_int("select_last_index", 0),
                ],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_13_bfloat16() {
    assert_op_matches_ort(
        build_fixture_opset_13_bfloat16(),
        ExpectConvertOp::ConversionError,
        13,
    );
}
