/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

pub mod arg_max;
pub mod arg_min;
pub mod reduce_l1;
pub mod reduce_l2;
pub mod reduce_log_sum;
pub mod reduce_log_sum_exp;
pub mod reduce_max;
pub mod reduce_mean;
pub mod reduce_min;
pub mod reduce_prod;
pub mod reduce_sum;
pub mod reduce_sum_square;
