/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `ReduceSum` operator conversion tests (fixture opsets: 12, 26, 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_12() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        12,
        graph(
            "test_ReduceSum_graph",
            vec![f32_input("data", &[1, 2])],
            vec![f32_output("reduced", &[2])],
            vec![node(
                "ReduceSum",
                "test_ReduceSum",
                &["data"],
                &["reduced"],
                &[attr_int("keepdims", 1)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_12() {
    assert_op_matches_ort(build_fixture_opset_12(), ExpectConvertOp::Success, 12);
}

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_ReduceSum_graph",
            vec![f32_input("data", &[1, 2])],
            vec![f32_output("reduced", &[2])],
            vec![node(
                "ReduceSum",
                "test_ReduceSum",
                &["data"],
                &["reduced"],
                &[attr_int("keepdims", 1), attr_int("noop_with_empty_axes", 0)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::Success, 26);
}

fn build_fixture_opset_26_float16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_ReduceSum_graph",
            vec![f16_input("data", &[1, 2])],
            vec![f16_output("reduced", &[2])],
            vec![node(
                "ReduceSum",
                "test_ReduceSum",
                &["data"],
                &["reduced"],
                &[attr_int("keepdims", 1), attr_int("noop_with_empty_axes", 0)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_26_float16() {
    assert_op_matches_ort(
        build_fixture_opset_26_float16(),
        ExpectConvertOp::Success,
        26,
    );
}
