/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `ReduceLogSum` operator conversion tests (fixture opsets: 13, 18, 18, 13).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_13() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        13,
        graph(
            "test_ReduceLogSum_graph",
            vec![f32_input("data", &[1, 2])],
            vec![f32_output("reduced", &[2])],
            vec![node(
                "ReduceLogSum",
                "test_ReduceLogSum",
                &["data"],
                &["reduced"],
                &[attr_int("keepdims", 1)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_13() {
    assert_op_matches_ort(build_fixture_opset_13(), ExpectConvertOp::Success, 13);
}

fn build_fixture_opset_18() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        18,
        graph(
            "test_ReduceLogSum_graph",
            vec![f32_input("data", &[1, 2])],
            vec![f32_output("reduced", &[2])],
            vec![node(
                "ReduceLogSum",
                "test_ReduceLogSum",
                &["data"],
                &["reduced"],
                &[attr_int("keepdims", 1), attr_int("noop_with_empty_axes", 0)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_18() {
    assert_op_matches_ort(build_fixture_opset_18(), ExpectConvertOp::Success, 18);
}

fn build_fixture_opset_18_float16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        18,
        graph(
            "test_ReduceLogSum_graph",
            vec![f16_input("data", &[1, 2])],
            vec![f16_output("reduced", &[2])],
            vec![node(
                "ReduceLogSum",
                "test_ReduceLogSum",
                &["data"],
                &["reduced"],
                &[attr_int("keepdims", 1), attr_int("noop_with_empty_axes", 0)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_18_float16() {
    assert_op_matches_ort(
        build_fixture_opset_18_float16(),
        ExpectConvertOp::Success,
        18,
    );
}

fn build_fixture_opset_13_bfloat16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        13,
        graph(
            "test_ReduceLogSum_graph",
            vec![bf16_input("data", &[1, 2])],
            vec![bf16_output("reduced", &[2])],
            vec![node(
                "ReduceLogSum",
                "test_ReduceLogSum",
                &["data"],
                &["reduced"],
                &[attr_int("keepdims", 1)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_13_bfloat16() {
    assert_op_matches_ort(
        build_fixture_opset_13_bfloat16(),
        ExpectConvertOp::ConversionError,
        13,
    );
}
