/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `ReduceMax` operator conversion tests (fixture opsets: 17, 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_17() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        17,
        graph(
            "test_ReduceMax_graph",
            vec![f32_input("data", &[1, 2])],
            vec![f32_output("reduced", &[2])],
            vec![node(
                "ReduceMax",
                "test_ReduceMax",
                &["data"],
                &["reduced"],
                &[attr_int("keepdims", 1)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_17() {
    assert_op_matches_ort(build_fixture_opset_17(), ExpectConvertOp::Success, 17);
}

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_ReduceMax_graph",
            vec![f32_input("data", &[1, 2])],
            vec![f32_output("reduced", &[2])],
            vec![node(
                "ReduceMax",
                "test_ReduceMax",
                &["data"],
                &["reduced"],
                &[attr_int("keepdims", 1), attr_int("noop_with_empty_axes", 0)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::Success, 26);
}
