/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `LpPool` operator conversion tests (fixture opsets: 17, 26, 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_17() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        17,
        graph(
            "test_LpPool_graph",
            vec![f32_input("X", &[1, 1, 4, 4])],
            vec![f32_output("Y", &[1, 1, 4, 4])],
            vec![node(
                "LpPool",
                "test_LpPool",
                &["X"],
                &["Y"],
                &[
                    attr_ints("kernel_shape", &[2, 2]),
                    attr_string("auto_pad", "NOTSET"),
                    attr_int("p", 2),
                ],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_17() {
    assert_op_matches_ort(build_fixture_opset_17(), ExpectConvertOp::Success, 17);
}

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_LpPool_graph",
            vec![f32_input("X", &[1, 1, 4, 4])],
            vec![f32_output("Y", &[1, 1, 4, 4])],
            vec![node(
                "LpPool",
                "test_LpPool",
                &["X"],
                &["Y"],
                &[
                    attr_ints("kernel_shape", &[2, 2]),
                    attr_string("auto_pad", "NOTSET"),
                    attr_int("p", 2),
                    attr_int("ceil_mode", 0),
                ],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::Success, 26);
}

fn build_fixture_opset_26_float16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_LpPool_graph",
            vec![f16_input("X", &[1, 1, 4, 4])],
            vec![f16_output("Y", &[1, 1, 4, 4])],
            vec![node(
                "LpPool",
                "test_LpPool",
                &["X"],
                &["Y"],
                &[
                    attr_ints("kernel_shape", &[2, 2]),
                    attr_string("auto_pad", "NOTSET"),
                    attr_int("p", 2),
                    attr_int("ceil_mode", 0),
                ],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_26_float16() {
    assert_op_matches_ort(
        build_fixture_opset_26_float16(),
        ExpectConvertOp::Success,
        26,
    );
}
