/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `MaxUnpool` operator conversion test (fixture opset 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

// Fixture builder failed at codegen: Node(test) with schema(::MaxUnpool:22) has input size 1 not in range [min=2, max=3]. ==> Context: Bad node spec for node. Name: test OpType: MaxUnpool
#[test]
#[ignore = "fixture builder failed at codegen: Node test with schema ::MaxUnpool:22 has input size 1 not in range min 2 max 3 . Context: Bad node spec for node. Name: "]
fn opset26() {}
