/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `MaxRoiPool` operator conversion tests (fixture opsets: 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_MaxRoiPool_graph",
            vec![f32_input("X", &[1, 1, 4, 4]), f32_input("rois", &[2, 4])],
            vec![f32_output("Y", &[2, 1, 2, 2])],
            vec![node(
                "MaxRoiPool",
                "test",
                &["X", "rois"],
                &["Y"],
                &[
                    attr_ints("pooled_shape", &[2, 2]),
                    attr_float("spatial_scale", 1.0),
                ],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::UnsupportedOp, 26);
}
