/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `MaxPool` operator conversion tests (fixture opsets: 9, 22, 22, 22).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_9() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        9,
        graph(
            "test_MaxPool_graph",
            vec![f32_input("X", &[1, 1, 4, 4])],
            vec![f32_output("Y", &[1, 1, 4, 4])],
            vec![node(
                "MaxPool",
                "test_MaxPool",
                &["X"],
                &["Y"],
                &[
                    attr_ints("kernel_shape", &[2, 2]),
                    attr_string("auto_pad", "NOTSET"),
                    attr_int("storage_order", 0),
                ],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_9() {
    assert_op_matches_ort(build_fixture_opset_9(), ExpectConvertOp::Success, 9);
}

fn build_fixture_opset_22() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        22,
        graph(
            "test_MaxPool_graph",
            vec![f32_input("X", &[1, 1, 4, 4])],
            vec![f32_output("Y", &[1, 1, 4, 4])],
            vec![node(
                "MaxPool",
                "test_MaxPool",
                &["X"],
                &["Y"],
                &[
                    attr_ints("kernel_shape", &[2, 2]),
                    attr_string("auto_pad", "NOTSET"),
                    attr_int("ceil_mode", 0),
                    attr_int("storage_order", 0),
                ],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_22() {
    assert_op_matches_ort(build_fixture_opset_22(), ExpectConvertOp::Success, 22);
}

fn build_fixture_opset_22_float16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        22,
        graph(
            "test_MaxPool_graph",
            vec![f16_input("X", &[1, 1, 4, 4])],
            vec![f16_output("Y", &[1, 1, 4, 4])],
            vec![node(
                "MaxPool",
                "test_MaxPool",
                &["X"],
                &["Y"],
                &[
                    attr_ints("kernel_shape", &[2, 2]),
                    attr_string("auto_pad", "NOTSET"),
                    attr_int("ceil_mode", 0),
                    attr_int("storage_order", 0),
                ],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_22_float16() {
    assert_op_matches_ort(
        build_fixture_opset_22_float16(),
        ExpectConvertOp::Success,
        22,
    );
}

fn build_fixture_opset_22_bfloat16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        22,
        graph(
            "test_MaxPool_graph",
            vec![bf16_input("X", &[1, 1, 4, 4])],
            vec![bf16_output("Y", &[1, 1, 4, 4])],
            vec![node(
                "MaxPool",
                "test_MaxPool",
                &["X"],
                &["Y"],
                &[
                    attr_ints("kernel_shape", &[2, 2]),
                    attr_string("auto_pad", "NOTSET"),
                    attr_int("ceil_mode", 0),
                    attr_int("storage_order", 0),
                ],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_22_bfloat16() {
    assert_op_matches_ort(
        build_fixture_opset_22_bfloat16(),
        ExpectConvertOp::ConversionError,
        22,
    );
}
