/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `MaxPool` operator conversion tests (fixture opsets: 9, 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_9() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        9,
        graph(
            "test_MaxPool_graph",
            vec![
                f32_input("X", &[1, 1, 4, 4]),
            ],
            vec![
                f32_output("Y", &[1, 1, 4, 4]),
            ],
            vec![
                node(
                    "MaxPool",
                    "test_MaxPool",
                    &["X"],
                    &["Y"],
                    &[
                        attr_ints("kernel_shape", &[2, 2]),
                        attr_string("auto_pad", "NOTSET"),
                        attr_int("storage_order", 0),
                    ],
                ),
            ],
            vec![
            ],
        ),
    )
}

#[test]
fn convert_op_opset_9() {
    assert_op_matches_ort(build_fixture_opset_9(), ExpectConvertOp::Success, 9);
}

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_MaxPool_graph",
            vec![
                f32_input("X", &[1, 1, 4, 4]),
            ],
            vec![
                f32_output("Y", &[1, 1, 4, 4]),
            ],
            vec![
                node(
                    "MaxPool",
                    "test_MaxPool",
                    &["X"],
                    &["Y"],
                    &[
                        attr_ints("kernel_shape", &[2, 2]),
                        attr_string("auto_pad", "NOTSET"),
                        attr_int("ceil_mode", 0),
                        attr_int("storage_order", 0),
                    ],
                ),
            ],
            vec![
            ],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::Success, 26);
}
