/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `MaxUnpool` operator conversion tests (fixture opsets: 22).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_22() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        22,
        graph(
            "test_MaxUnpool_graph",
            vec![f32_input("X", &[1, 1, 2, 2])],
            vec![f32_output("Y", &[1, 1, 4, 4])],
            vec![node(
                "MaxUnpool",
                "test",
                &["X", "I"],
                &["Y"],
                &[
                    attr_ints("kernel_shape", &[2, 2]),
                    attr_ints("strides", &[2, 2]),
                ],
            )],
            vec![i64_init("I", &[1, 1, 2, 2], &[0, 1, 4, 5])],
        ),
    )
}

#[test]
fn convert_op_opset_22() {
    assert_op_matches_ort(build_fixture_opset_22(), ExpectConvertOp::UnsupportedOp, 22);
}
