/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

pub mod average_pool;
pub mod global_average_pool;
pub mod global_lp_pool;
pub mod global_max_pool;
pub mod lp_pool;
pub mod max_pool;
pub mod max_roi_pool;
pub mod max_unpool;
pub mod roi_align;
