/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `RoiAlign` operator conversion tests (fixture opsets: 15, 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_15() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        15,
        graph(
            "test_RoiAlign_graph",
            vec![f32_input("X", &[1, 1, 4, 4]), f32_input("rois", &[2, 4])],
            vec![f32_output("Y", &[2, 1, 2, 2])],
            vec![node(
                "RoiAlign",
                "test",
                &["X", "rois", "batch_indices"],
                &["Y"],
                &[attr_int("output_height", 2), attr_int("output_width", 2)],
            )],
            vec![i64_init("batch_indices", &[2], &[0, 0])],
        ),
    )
}

#[test]
fn convert_op_opset_15() {
    assert_op_matches_ort(build_fixture_opset_15(), ExpectConvertOp::UnsupportedOp, 15);
}

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_RoiAlign_graph",
            vec![f32_input("X", &[1, 1, 4, 4]), f32_input("rois", &[2, 4])],
            vec![f32_output("Y", &[2, 1, 2, 2])],
            vec![node(
                "RoiAlign",
                "test",
                &["X", "rois", "batch_indices"],
                &["Y"],
                &[attr_int("output_height", 2), attr_int("output_width", 2)],
            )],
            vec![i64_init("batch_indices", &[2], &[0, 0])],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::UnsupportedOp, 26);
}
