/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `RegexFullMatch` operator conversion test (fixture opset 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

// Fixture builder failed at codegen: Node(test) with schema(::RegexFullMatch:20) has input size 2 not in range [min=1, max=1]. ==> Context: Bad node spec for node. Name: test OpType: RegexFullMatch
#[test]
#[ignore = "fixture builder failed at codegen: Node test with schema ::RegexFullMatch:20 has input size 2 not in range min 1 max 1 . Context: Bad node spec for node. N"]
fn opset26() {}
