/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `StringNormalizer` operator conversion tests (fixture opsets: 10).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_10() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        10,
        graph(
            "test_StringNormalizer_graph",
            vec![],
            vec![string_output("Y", &[2])],
            vec![node(
                "StringNormalizer",
                "test",
                &["X"],
                &["Y"],
                &[
                    attr_string("case_change_action", "UPPER"),
                    attr_int("is_case_sensitive", 0),
                    attr_string("locale", "en_US"),
                ],
            )],
            vec![string_init("X", &[2], &["Hello", "World"])],
        ),
    )
}

#[test]
fn convert_op_opset_10() {
    assert_op_matches_ort(build_fixture_opset_10(), ExpectConvertOp::UnsupportedOp, 10);
}
