/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `StringConcat` operator conversion tests (fixture opsets: 20).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_20() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        20,
        graph(
            "test_StringConcat_graph",
            vec![],
            vec![string_output("Z", &[4])],
            vec![node("StringConcat", "test", &["X", "Y"], &["Z"], &[])],
            vec![
                string_init("X", &[2], &["a", "b"]),
                string_init("Y", &[2], &["c", "d"]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_20() {
    assert_op_matches_ort(build_fixture_opset_20(), ExpectConvertOp::UnsupportedOp, 20);
}
