/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `StringSplit` operator conversion tests (fixture opsets: 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_StringSplit_graph",
            vec![
            ],
            vec![
                string_output("Y", &[2, 2]),
                i64_output("Z", &[2, 2]),
            ],
            vec![
                node(
                    "StringSplit",
                    "test",
                    &["X"],
                    &["Y", "Z"],
                    &[],
                ),
            ],
            vec![
                string_init("X", &[2], &["a,b", "c,d"]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::UnsupportedOp, 26);
}
