/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `StringNormalizer` operator conversion test (fixture opset 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

// Fixture builder failed at codegen: Could not infer attribute `stopwords` type from empty iterator
#[test]
#[ignore = "fixture builder failed at codegen: Could not infer attribute stopwords type from empty iterator"]
fn opset26() {}
