/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `TfIdfVectorizer` operator conversion test (fixture opset 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

// Fixture builder failed at codegen: Required attribute 'mode' is missing. ==> Context: Bad node spec for node. Name: test OpType: TfIdfVectorizer
#[test]
#[ignore = "fixture builder failed at codegen: Required attribute mode is missing. Context: Bad node spec for node. Name: test OpType: TfIdfVectorizer"]
fn opset26() {}
