/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `TfIdfVectorizer` operator conversion tests (fixture opsets: 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_TfIdfVectorizer_graph",
            vec![
            ],
            vec![
                f32_output("Y", &[2, 3]),
            ],
            vec![
                node(
                    "TfIdfVectorizer",
                    "test",
                    &["X"],
                    &["Y"],
                    &[
                        attr_int("max_gram_length", 1),
                        attr_int("max_skip_count", 0),
                        attr_int("min_gram_length", 1),
                        attr_string("mode", "TFIDF"),
                        attr_ints("ngram_counts", &[1, 1, 1]),
                        attr_ints("ngram_indexes", &[0, 1, 2]),
                        attr_ints("pool_int64s", &[0, 1, 2]),
                    ],
                ),
            ],
            vec![
                string_init("X", &[2], &["a b", "b c"]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::UnsupportedOp, 26);
}
