/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `CastLike` operator conversion tests (fixture opsets: 15, 23, 25, 25, 15).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_15() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        15,
        graph(
            "test_CastLike_graph",
            vec![
                f32_input("input", &[1, 2]),
                f32_input("target_type", &[1, 2]),
            ],
            vec![f32_output("output", &[1, 2])],
            vec![node(
                "CastLike",
                "test_CastLike",
                &["input", "target_type"],
                &["output"],
                &[],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_15() {
    assert_op_matches_ort(build_fixture_opset_15(), ExpectConvertOp::Success, 15);
}

fn build_fixture_opset_23() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        23,
        graph(
            "test_CastLike_graph",
            vec![
                f32_input("input", &[1, 2]),
                f32_input("target_type", &[1, 2]),
            ],
            vec![f32_output("output", &[1, 2])],
            vec![node(
                "CastLike",
                "test_CastLike",
                &["input", "target_type"],
                &["output"],
                &[attr_int("saturate", 1)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_23() {
    assert_op_matches_ort(build_fixture_opset_23(), ExpectConvertOp::Success, 23);
}

fn build_fixture_opset_25() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        25,
        graph(
            "test_CastLike_graph",
            vec![
                f32_input("input", &[1, 2]),
                f32_input("target_type", &[1, 2]),
            ],
            vec![f32_output("output", &[1, 2])],
            vec![node(
                "CastLike",
                "test_CastLike",
                &["input", "target_type"],
                &["output"],
                &[attr_int("saturate", 1), attr_string("round_mode", "up")],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_25() {
    assert_op_matches_ort(build_fixture_opset_25(), ExpectConvertOp::Success, 25);
}

fn build_fixture_opset_25_float16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        25,
        graph(
            "test_CastLike_graph",
            vec![
                f16_input("input", &[1, 2]),
                f16_input("target_type", &[1, 2]),
            ],
            vec![f16_output("output", &[1, 2])],
            vec![node(
                "CastLike",
                "test_CastLike",
                &["input", "target_type"],
                &["output"],
                &[attr_int("saturate", 1), attr_string("round_mode", "up")],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_25_float16() {
    assert_op_matches_ort(
        build_fixture_opset_25_float16(),
        ExpectConvertOp::Success,
        25,
    );
}

fn build_fixture_opset_15_bfloat16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        15,
        graph(
            "test_CastLike_graph",
            vec![
                bf16_input("input", &[1, 2]),
                bf16_input("target_type", &[1, 2]),
            ],
            vec![bf16_output("output", &[1, 2])],
            vec![node(
                "CastLike",
                "test_CastLike",
                &["input", "target_type"],
                &["output"],
                &[],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_15_bfloat16() {
    assert_op_matches_ort(
        build_fixture_opset_15_bfloat16(),
        ExpectConvertOp::ConversionError,
        15,
    );
}
