/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Constant` operator conversion test (fixture opset 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_Constant_graph",
            vec![
            ],
            vec![
                f32_output("output", &[]),
            ],
            vec![
                node(
                    "Constant",
                    "test_Constant",
                    &[],
                    &["output"],
                    &[
                        attr_tensor("value", f32_init("value", &[], &[1.0])),
                    ],
                ),
            ],
            vec![
            ],
        ),
    )
}

#[test]
fn opset26() {
    assert_op_matches_ort(build_fixture(), ExpectConvertOp::Success, 18);
}
