/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `ConstantOfShape` operator conversion tests (fixture opsets: 25, 25).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_25() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        25,
        graph(
            "test_ConstantOfShape_graph",
            vec![],
            vec![f32_output("output", &[1, 2])],
            vec![node(
                "ConstantOfShape",
                "test",
                &["input"],
                &["output"],
                &[attr_tensor("value", f32_init("value", &[1], &[1.0]))],
            )],
            vec![i64_init("input", &[2], &[1, 2])],
        ),
    )
}

#[test]
fn convert_op_opset_25() {
    assert_op_matches_ort(build_fixture_opset_25(), ExpectConvertOp::Success, 25);
}

fn build_fixture_opset_25_float16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        25,
        graph(
            "test_ConstantOfShape_graph",
            vec![],
            vec![f16_output("output", &[1, 2])],
            vec![node(
                "ConstantOfShape",
                "test",
                &["input"],
                &["output"],
                &[attr_tensor("value", f16_init("value", &[1], &[15360]))],
            )],
            vec![i64_init("input", &[2], &[1, 2])],
        ),
    )
}

#[test]
fn convert_op_opset_25_float16() {
    assert_op_matches_ort(
        build_fixture_opset_25_float16(),
        ExpectConvertOp::Success,
        25,
    );
}
