/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Constant` operator conversion tests (fixture opsets: 9, 11, 25).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_9() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        9,
        graph(
            "test_Constant_graph",
            vec![],
            vec![f32_output("output", &[])],
            vec![node(
                "Constant",
                "test_Constant",
                &[],
                &["output"],
                &[attr_tensor("value", f32_init("value", &[], &[1.0]))],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_9() {
    assert_op_matches_ort(build_fixture_opset_9(), ExpectConvertOp::Success, 9);
}

fn build_fixture_opset_11() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        11,
        graph(
            "test_Constant_graph",
            vec![],
            vec![f32_output("output", &[])],
            vec![node(
                "Constant",
                "test_Constant",
                &[],
                &["output"],
                &[attr_tensor("value", f32_init("value", &[], &[1.0]))],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_11() {
    assert_op_matches_ort(build_fixture_opset_11(), ExpectConvertOp::Success, 11);
}

fn build_fixture_opset_25() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        25,
        graph(
            "test_Constant_graph",
            vec![],
            vec![f32_output("output", &[])],
            vec![node(
                "Constant",
                "test_Constant",
                &[],
                &["output"],
                &[attr_tensor("value", f32_init("value", &[], &[1.0]))],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_25() {
    assert_op_matches_ort(build_fixture_opset_25(), ExpectConvertOp::Success, 25);
}
