/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `GridSample` operator conversion test (fixture opset 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_GridSample_graph",
            vec![
                f32_input("X", &[1, 1, 4, 4]),
                f32_input("grid", &[1, 4, 4, 2]),
            ],
            vec![
                f32_output("Y", &[1, 1, 4, 4]),
            ],
            vec![
                node(
                    "GridSample",
                    "test",
                    &["X", "grid"],
                    &["Y"],
                    &[
                        attr_string("mode", "bilinear"),
                    ],
                ),
            ],
            vec![
            ],
        ),
    )
}

#[test]
fn opset26() {
    assert_op_matches_ort(build_fixture(), ExpectConvertOp::UnsupportedOp, 18);
}
