/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `ImageDecoder` operator conversion test (fixture opset 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_ImageDecoder_graph",
            vec![
            ],
            vec![
                u8_output("rgb", &[1, 1, 1]),
            ],
            vec![
                node(
                    "ImageDecoder",
                    "test",
                    &["encoded_stream"],
                    &["rgb"],
                    &[
                        attr_string("pixel_format", "RGB"),
                    ],
                ),
            ],
            vec![
                u8_init("encoded_stream", &[3], &[0, 0, 0]),
            ],
        ),
    )
}

#[test]
fn opset26() {
    assert_op_matches_ort(build_fixture(), ExpectConvertOp::UnsupportedOp, 18);
}
