/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

pub mod affine_grid;
pub mod cast;
pub mod cast_like;
pub mod constant;
pub mod constant_of_shape;
pub mod det;
pub mod eye_like;
pub mod grid_sample;
pub mod image_decoder;
pub mod non_zero;
pub mod one_hot;
pub mod optional;
pub mod optional_get_element;
pub mod optional_has_element;
pub mod pad;
pub mod range;
pub mod resize;
pub mod scatter_elements;
pub mod scatter_nd;
pub mod shape;
pub mod size;
pub mod slice;
pub mod tensor_scatter;
pub mod top_k;
pub mod trilu;
pub mod unique;
pub mod r#where;
