/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `OptionalHasElement` operator conversion tests (fixture opsets: 15, 18).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_15() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        15,
        graph(
            "test_OptionalHasElement_graph",
            vec![f32_input("input", &[1, 2])],
            vec![bool_output("output", &[1, 2])],
            vec![node(
                "OptionalHasElement",
                "test_OptionalHasElement",
                &["input"],
                &["output"],
                &[],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_15() {
    assert_op_matches_ort(build_fixture_opset_15(), ExpectConvertOp::UnsupportedOp, 15);
}

fn build_fixture_opset_18() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        18,
        graph(
            "test_OptionalHasElement_graph",
            vec![],
            vec![bool_output("output", &[1, 2])],
            vec![node(
                "OptionalHasElement",
                "test_OptionalHasElement",
                &[],
                &["output"],
                &[],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_18() {
    assert_op_matches_ort(build_fixture_opset_18(), ExpectConvertOp::UnsupportedOp, 18);
}
