/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Range` operator conversion tests (fixture opsets: 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_Range_graph",
            vec![
            ],
            vec![
                f32_output("output", &[3]),
            ],
            vec![
                node(
                    "Range",
                    "test",
                    &["start", "limit", "delta"],
                    &["output"],
                    &[],
                ),
            ],
            vec![
                f32_init("start", &[], &[0.5]),
                f32_init("limit", &[], &[2.0]),
                f32_init("delta", &[], &[0.5]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::Success, 26);
}
