/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Resize` operator conversion tests (fixture opsets: 13, 19, 19, 13).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_13() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        13,
        graph(
            "test_Resize_graph",
            vec![f32_input("X", &[1, 1, 4, 4])],
            vec![f32_output("Y", &[1, 1, 6, 6])],
            vec![node(
                "Resize",
                "test",
                &["X", "", "", "sizes"],
                &["Y"],
                &[attr_string("mode", "nearest")],
            )],
            vec![i64_init("sizes", &[4], &[1, 1, 6, 6])],
        ),
    )
}

#[test]
fn convert_op_opset_13() {
    assert_op_matches_ort(build_fixture_opset_13(), ExpectConvertOp::Success, 13);
}

fn build_fixture_opset_19() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        19,
        graph(
            "test_Resize_graph",
            vec![f32_input("X", &[1, 1, 4, 4])],
            vec![f32_output("Y", &[1, 1, 6, 6])],
            vec![node(
                "Resize",
                "test",
                &["X", "", "", "sizes"],
                &["Y"],
                &[attr_string("mode", "nearest")],
            )],
            vec![i64_init("sizes", &[4], &[1, 1, 6, 6])],
        ),
    )
}

#[test]
fn convert_op_opset_19() {
    assert_op_matches_ort(build_fixture_opset_19(), ExpectConvertOp::Success, 19);
}

fn build_fixture_opset_19_float16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        19,
        graph(
            "test_Resize_graph",
            vec![f16_input("X", &[1, 1, 4, 4])],
            vec![f16_output("Y", &[1, 1, 6, 6])],
            vec![node(
                "Resize",
                "test",
                &["X", "", "", "sizes"],
                &["Y"],
                &[attr_string("mode", "nearest")],
            )],
            vec![i64_init("sizes", &[4], &[1, 1, 6, 6])],
        ),
    )
}

#[test]
fn convert_op_opset_19_float16() {
    assert_op_matches_ort(
        build_fixture_opset_19_float16(),
        ExpectConvertOp::Success,
        19,
    );
}

fn build_fixture_opset_13_bfloat16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        13,
        graph(
            "test_Resize_graph",
            vec![bf16_input("X", &[1, 1, 4, 4])],
            vec![bf16_output("Y", &[1, 1, 6, 6])],
            vec![node(
                "Resize",
                "test",
                &["X", "", "", "sizes"],
                &["Y"],
                &[attr_string("mode", "nearest")],
            )],
            vec![i64_init("sizes", &[4], &[1, 1, 6, 6])],
        ),
    )
}

#[test]
fn convert_op_opset_13_bfloat16() {
    assert_op_matches_ort(
        build_fixture_opset_13_bfloat16(),
        ExpectConvertOp::ConversionError,
        13,
    );
}
