/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `ScatterND` operator conversion tests (fixture opsets: 15, 26, 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_15() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        15,
        graph(
            "test_ScatterND_graph",
            vec![f32_input("data", &[1, 2]), f32_input("updates", &[1, 2])],
            vec![f32_output("output", &[1, 2])],
            vec![node(
                "ScatterND",
                "test_ScatterND",
                &["data", "indices", "updates"],
                &["output"],
                &[],
            )],
            vec![i64_init("indices", &[1, 1], &[0])],
        ),
    )
}

#[test]
fn convert_op_opset_15() {
    assert_op_matches_ort(build_fixture_opset_15(), ExpectConvertOp::Success, 15);
}

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_ScatterND_graph",
            vec![f32_input("data", &[1, 2]), f32_input("updates", &[1, 2])],
            vec![f32_output("output", &[1, 2])],
            vec![node(
                "ScatterND",
                "test_ScatterND",
                &["data", "indices", "updates"],
                &["output"],
                &[attr_string("reduction", "none")],
            )],
            vec![i64_init("indices", &[1, 1], &[0])],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::Success, 26);
}

fn build_fixture_opset_26_float16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_ScatterND_graph",
            vec![f16_input("data", &[1, 2]), f16_input("updates", &[1, 2])],
            vec![f16_output("output", &[1, 2])],
            vec![node(
                "ScatterND",
                "test_ScatterND",
                &["data", "indices", "updates"],
                &["output"],
                &[attr_string("reduction", "none")],
            )],
            vec![i64_init("indices", &[1, 1], &[0])],
        ),
    )
}

#[test]
fn convert_op_opset_26_float16() {
    assert_op_matches_ort(
        build_fixture_opset_26_float16(),
        ExpectConvertOp::Success,
        26,
    );
}
