/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `ScatterElements` operator conversion tests (fixture opsets: 15, 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_15() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        15,
        graph(
            "test_ScatterElements_graph",
            vec![f32_input("data", &[1, 2]), f32_input("updates", &[1, 2])],
            vec![f32_output("output", &[1, 2])],
            vec![node(
                "ScatterElements",
                "test_ScatterElements",
                &["data", "indices", "updates"],
                &["output"],
                &[attr_int("axis", 0)],
            )],
            vec![i64_init("indices", &[1, 2], &[0, 0])],
        ),
    )
}

#[test]
fn convert_op_opset_15() {
    assert_op_matches_ort(build_fixture_opset_15(), ExpectConvertOp::UnsupportedOp, 15);
}

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_ScatterElements_graph",
            vec![f32_input("data", &[1, 2]), f32_input("updates", &[1, 2])],
            vec![f32_output("output", &[1, 2])],
            vec![node(
                "ScatterElements",
                "test_ScatterElements",
                &["data", "indices", "updates"],
                &["output"],
                &[attr_int("axis", 0), attr_string("reduction", "none")],
            )],
            vec![i64_init("indices", &[1, 2], &[0, 0])],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::UnsupportedOp, 26);
}
