/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Shape` operator conversion tests (fixture opsets: 14, 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_14() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        14,
        graph(
            "test_Shape_graph",
            vec![f32_input("data", &[1, 2])],
            vec![i64_output("shape", &[2])],
            vec![node("Shape", "test_Shape", &["data"], &["shape"], &[])],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_14() {
    assert_op_matches_ort(build_fixture_opset_14(), ExpectConvertOp::Success, 14);
}

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_Shape_graph",
            vec![f32_input("data", &[1, 2])],
            vec![i64_output("shape", &[2])],
            vec![node(
                "Shape",
                "test_Shape",
                &["data"],
                &["shape"],
                &[attr_int("start", 0)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::Success, 26);
}
