/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `TensorScatter` operator conversion tests (fixture opsets: 24).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_24() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        24,
        graph(
            "test_TensorScatter_graph",
            vec![f32_input("data", &[1, 2]), f32_input("updates", &[1, 2])],
            vec![f32_output("output", &[1, 2])],
            vec![node(
                "TensorScatter",
                "test",
                &["data", "indices", "updates"],
                &["output"],
                &[],
            )],
            vec![i64_init("indices", &[], &[0])],
        ),
    )
}

#[test]
fn convert_op_opset_24() {
    assert_op_matches_ort(build_fixture_opset_24(), ExpectConvertOp::UnsupportedOp, 24);
}
