/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `TopK` operator conversion test (fixture opset 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_TopK_graph",
            vec![
                f32_input("X", &[1, 2]),
            ],
            vec![
                f32_output("Values", &[1]),
                i64_output("Indices", &[1]),
            ],
            vec![
                node(
                    "TopK",
                    "test",
                    &["X", "K"],
                    &["Values", "Indices"],
                    &[
                        attr_int("axis", 0),
                    ],
                ),
            ],
            vec![
                i64_init("K", &[], &[1]),
            ],
        ),
    )
}

#[test]
fn opset26() {
    assert_op_matches_ort(build_fixture(), ExpectConvertOp::UnsupportedOp, 18);
}
