/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Trilu` operator conversion tests (fixture opsets: 14, 14, 14).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_14() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        14,
        graph(
            "test_Trilu_graph",
            vec![f32_input("input", &[1, 2])],
            vec![f32_output("output", &[1, 2])],
            vec![node(
                "Trilu",
                "test_Trilu",
                &["input"],
                &["output"],
                &[attr_int("upper", 1)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_14() {
    assert_op_matches_ort(build_fixture_opset_14(), ExpectConvertOp::Success, 14);
}

fn build_fixture_opset_14_float16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        14,
        graph(
            "test_Trilu_graph",
            vec![f16_input("input", &[1, 2])],
            vec![f16_output("output", &[1, 2])],
            vec![node(
                "Trilu",
                "test_Trilu",
                &["input"],
                &["output"],
                &[attr_int("upper", 1)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_14_float16() {
    assert_op_matches_ort(
        build_fixture_opset_14_float16(),
        ExpectConvertOp::Success,
        14,
    );
}

fn build_fixture_opset_14_bfloat16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        14,
        graph(
            "test_Trilu_graph",
            vec![bf16_input("input", &[1, 2])],
            vec![bf16_output("output", &[1, 2])],
            vec![node(
                "Trilu",
                "test_Trilu",
                &["input"],
                &["output"],
                &[attr_int("upper", 1)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_14_bfloat16() {
    assert_op_matches_ort(
        build_fixture_opset_14_bfloat16(),
        ExpectConvertOp::ConversionError,
        14,
    );
}
