/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Unique` operator conversion tests (fixture opsets: 11).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_11() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        11,
        graph(
            "test_Unique_graph",
            vec![f32_input("X", &[1, 2])],
            vec![
                f32_output("Y", &[1, 2]),
                i64_output("indices", &[1, 2]),
                i64_output("inverse_indices", &[1, 2]),
                i64_output("counts", &[1, 2]),
            ],
            vec![node(
                "Unique",
                "test_Unique",
                &["X"],
                &["Y", "indices", "inverse_indices", "counts"],
                &[attr_int("sorted", 1)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_11() {
    assert_op_matches_ort(build_fixture_opset_11(), ExpectConvertOp::UnsupportedOp, 11);
}
