/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Dropout` operator conversion tests (fixture opsets: 9, 10, 22).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_9() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        9,
        graph(
            "test_Dropout_graph",
            vec![f32_input("data", &[1, 2])],
            vec![f32_output("output", &[1, 2]), bool_output("mask", &[1, 2])],
            vec![node(
                "Dropout",
                "test_Dropout",
                &["data"],
                &["output", "mask"],
                &[attr_float("ratio", 0.5)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_9() {
    assert_op_matches_ort(build_fixture_opset_9(), ExpectConvertOp::UnsupportedOp, 9);
}

fn build_fixture_opset_10() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        10,
        graph(
            "test_Dropout_graph",
            vec![f32_input("data", &[1, 2])],
            vec![f32_output("output", &[1, 2]), bool_output("mask", &[1, 2])],
            vec![node(
                "Dropout",
                "test_Dropout",
                &["data"],
                &["output", "mask"],
                &[attr_float("ratio", 0.5)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_10() {
    assert_op_matches_ort(build_fixture_opset_10(), ExpectConvertOp::UnsupportedOp, 10);
}

fn build_fixture_opset_22() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        22,
        graph(
            "test_Dropout_graph",
            vec![f32_input("data", &[1, 2])],
            vec![f32_output("output", &[1, 2]), bool_output("mask", &[1, 2])],
            vec![node(
                "Dropout",
                "test_Dropout",
                &["data"],
                &["output", "mask"],
                &[],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_22() {
    assert_op_matches_ort(build_fixture_opset_22(), ExpectConvertOp::UnsupportedOp, 22);
}
