/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

pub mod bernoulli;
pub mod dropout;
pub mod multinomial;
pub mod random_normal;
pub mod random_normal_like;
pub mod random_uniform;
pub mod random_uniform_like;
