/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `RandomNormal` operator conversion test (fixture opset 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

// Fixture builder failed at codegen: Node(test_RandomNormal) with schema(::RandomNormal:22) has input size 1 not in range [min=0, max=0]. ==> Context: Bad node spec for node. Name: test_RandomNormal OpType: RandomNormal
#[test]
#[ignore = "fixture builder failed at codegen: Node test_RandomNormal with schema ::RandomNormal:22 has input size 1 not in range min 0 max 0 . Context: Bad node spec "]
fn opset26() {}
