/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `BitShift` operator conversion test (fixture opset 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_BitShift_graph",
            vec![
            ],
            vec![
                u8_output("Z", &[1, 2]),
            ],
            vec![
                node(
                    "BitShift",
                    "test_BitShift",
                    &["X", "Y"],
                    &["Z"],
                    &[
                        attr_string("direction", "LEFT"),
                    ],
                ),
            ],
            vec![
                u8_init("X", &[2], &[1, 2]),
                u8_init("Y", &[], &[1]),
            ],
        ),
    )
}

#[test]
fn opset26() {
    assert_op_matches_ort(build_fixture(), ExpectConvertOp::UnsupportedOp, 18);
}
