/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Acosh` operator conversion tests (fixture opsets: 26, 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_Acosh_graph",
            vec![f32_input("input", &[1, 2])],
            vec![f32_output("output", &[1, 2])],
            vec![node("Acosh", "test_Acosh", &["input"], &["output"], &[])],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::Success, 26);
}

fn build_fixture_opset_26_float16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_Acosh_graph",
            vec![f16_input("input", &[1, 2])],
            vec![f16_output("output", &[1, 2])],
            vec![node("Acosh", "test_Acosh", &["input"], &["output"], &[])],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_26_float16() {
    assert_op_matches_ort(
        build_fixture_opset_26_float16(),
        ExpectConvertOp::Success,
        26,
    );
}
