/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Atan` operator conversion tests (fixture opsets: 22).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_22() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        22,
        graph(
            "test_Atan_graph",
            vec![f32_input("input", &[1, 2])],
            vec![f32_output("output", &[1, 2])],
            vec![node("Atan", "test_Atan", &["input"], &["output"], &[])],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_22() {
    assert_op_matches_ort(build_fixture_opset_22(), ExpectConvertOp::UnsupportedOp, 22);
}
