/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Celu` operator conversion tests (fixture opsets: 12, 12).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_12() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        12,
        graph(
            "test_Celu_graph",
            vec![f32_input("X", &[1, 2])],
            vec![f32_output("Y", &[1, 2])],
            vec![node(
                "Celu",
                "test_Celu",
                &["X"],
                &["Y"],
                &[attr_float("alpha", 1.0)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_12() {
    assert_op_matches_ort(build_fixture_opset_12(), ExpectConvertOp::Success, 12);
}

fn build_fixture_opset_12_float16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        12,
        graph(
            "test_Celu_graph",
            vec![f16_input("X", &[1, 2])],
            vec![f16_output("Y", &[1, 2])],
            vec![node(
                "Celu",
                "test_Celu",
                &["X"],
                &["Y"],
                &[attr_float("alpha", 1.0)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_12_float16() {
    assert_op_matches_ort(
        build_fixture_opset_12_float16(),
        ExpectConvertOp::Success,
        12,
    );
}
