/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Clip` operator conversion tests (fixture opsets: 9, 13, 13, 13).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_9() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        9,
        graph(
            "test_Clip_graph",
            vec![f32_input("input", &[1, 2])],
            vec![f32_output("output", &[1, 2])],
            vec![node(
                "Clip",
                "test_Clip",
                &["input"],
                &["output"],
                &[
                    attr_float("min", -3.4028234663852886e+38),
                    attr_float("max", 3.4028234663852886e+38),
                ],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_9() {
    assert_op_matches_ort(build_fixture_opset_9(), ExpectConvertOp::Success, 9);
}

fn build_fixture_opset_13() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        13,
        graph(
            "test_Clip_graph",
            vec![f32_input("input", &[1, 2])],
            vec![f32_output("output", &[1, 2])],
            vec![node("Clip", "test_Clip", &["input"], &["output"], &[])],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_13() {
    assert_op_matches_ort(build_fixture_opset_13(), ExpectConvertOp::Success, 13);
}

fn build_fixture_opset_13_float16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        13,
        graph(
            "test_Clip_graph",
            vec![f16_input("input", &[1, 2])],
            vec![f16_output("output", &[1, 2])],
            vec![node("Clip", "test_Clip", &["input"], &["output"], &[])],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_13_float16() {
    assert_op_matches_ort(
        build_fixture_opset_13_float16(),
        ExpectConvertOp::Success,
        13,
    );
}

fn build_fixture_opset_13_bfloat16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        13,
        graph(
            "test_Clip_graph",
            vec![bf16_input("input", &[1, 2])],
            vec![bf16_output("output", &[1, 2])],
            vec![node("Clip", "test_Clip", &["input"], &["output"], &[])],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_13_bfloat16() {
    assert_op_matches_ort(
        build_fixture_opset_13_bfloat16(),
        ExpectConvertOp::ConversionError,
        13,
    );
}
