/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Clip` operator conversion tests (fixture opsets: 10, 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_10() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        10,
        graph(
            "test_Clip_graph",
            vec![
                f32_input("input", &[1, 2]),
            ],
            vec![
                f32_output("output", &[1, 2]),
            ],
            vec![
                node(
                    "Clip",
                    "test_Clip",
                    &["input"],
                    &["output"],
                    &[
                        attr_float("min", -3.4028234663852886e+38),
                        attr_float("max", 3.4028234663852886e+38),
                    ],
                ),
            ],
            vec![
            ],
        ),
    )
}

#[test]
fn convert_op_opset_10() {
    assert_op_matches_ort(build_fixture_opset_10(), ExpectConvertOp::UnsupportedOp, 10);
}

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_Clip_graph",
            vec![
                f32_input("input", &[1, 2]),
            ],
            vec![
                f32_output("output", &[1, 2]),
            ],
            vec![
                node(
                    "Clip",
                    "test_Clip",
                    &["input"],
                    &["output"],
                    &[],
                ),
            ],
            vec![
            ],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::UnsupportedOp, 26);
}
