/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Cos` operator conversion test (fixture opset 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_Cos_graph",
            vec![
                f32_input("input", &[1, 2]),
            ],
            vec![
                f32_output("output", &[1, 2]),
            ],
            vec![
                node(
                    "Cos",
                    "test_Cos",
                    &["input"],
                    &["output"],
                    &[],
                ),
            ],
            vec![
            ],
        ),
    )
}

#[test]
fn opset26() {
    assert_op_matches_ort(build_fixture(), ExpectConvertOp::Success, 18);
}
