/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `HardSigmoid` operator conversion test (fixture opset 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_HardSigmoid_graph",
            vec![
                f32_input("X", &[1, 2]),
            ],
            vec![
                f32_output("Y", &[1, 2]),
            ],
            vec![
                node(
                    "HardSigmoid",
                    "test_HardSigmoid",
                    &["X"],
                    &["Y"],
                    &[
                        attr_float("alpha", 0.20000000298023224),
                        attr_float("beta", 0.5),
                    ],
                ),
            ],
            vec![
            ],
        ),
    )
}

#[test]
fn opset26() {
    assert_op_matches_ort(build_fixture(), ExpectConvertOp::UnsupportedOp, 18);
}
