/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Shrink` operator conversion tests (fixture opsets: 9, 9).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_9() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        9,
        graph(
            "test_Shrink_graph",
            vec![f32_input("input", &[1, 2])],
            vec![f32_output("output", &[1, 2])],
            vec![node(
                "Shrink",
                "test_Shrink",
                &["input"],
                &["output"],
                &[attr_float("lambd", 0.5), attr_float("bias", 0.0)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_9() {
    assert_op_matches_ort(build_fixture_opset_9(), ExpectConvertOp::Success, 9);
}

fn build_fixture_opset_9_float16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        9,
        graph(
            "test_Shrink_graph",
            vec![f16_input("input", &[1, 2])],
            vec![f16_output("output", &[1, 2])],
            vec![node(
                "Shrink",
                "test_Shrink",
                &["input"],
                &["output"],
                &[attr_float("lambd", 0.5), attr_float("bias", 0.0)],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_9_float16() {
    assert_op_matches_ort(build_fixture_opset_9_float16(), ExpectConvertOp::Success, 9);
}
