/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Swish` operator conversion tests (fixture opsets: 24, 24, 24).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_24() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        24,
        graph(
            "test_Swish_graph",
            vec![f32_input("X", &[1, 2])],
            vec![f32_output("Y", &[1, 2])],
            vec![node("Swish", "test", &["X"], &["Y"], &[])],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_24() {
    assert_op_matches_ort(build_fixture_opset_24(), ExpectConvertOp::Success, 24);
}

fn build_fixture_opset_24_float16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        24,
        graph(
            "test_Swish_graph",
            vec![f16_input("X", &[1, 2])],
            vec![f16_output("Y", &[1, 2])],
            vec![node("Swish", "test", &["X"], &["Y"], &[])],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_24_float16() {
    assert_op_matches_ort(
        build_fixture_opset_24_float16(),
        ExpectConvertOp::Success,
        24,
    );
}

fn build_fixture_opset_24_bfloat16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        24,
        graph(
            "test_Swish_graph",
            vec![bf16_input("X", &[1, 2])],
            vec![bf16_output("Y", &[1, 2])],
            vec![node("Swish", "test", &["X"], &["Y"], &[])],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_24_bfloat16() {
    assert_op_matches_ort(
        build_fixture_opset_24_bfloat16(),
        ExpectConvertOp::ConversionError,
        24,
    );
}
