/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `SoftmaxCrossEntropyLoss` operator conversion tests (fixture opsets: 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_NegativeLogLikelihoodLoss_graph",
            vec![
                f32_input("input", &[2, 3]),
                i32_input("target", &[2]),
            ],
            vec![
                f32_output("output", &[]),
            ],
            vec![
                node(
                    "NegativeLogLikelihoodLoss",
                    "test",
                    &["input", "target"],
                    &["output"],
                    &[
                        attr_string("reduction", "mean"),
                    ],
                ),
            ],
            vec![
            ],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::UnsupportedOp, 26);
}
