/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Equal` operator conversion tests (fixture opsets: 19, 19, 13).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_19() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        19,
        graph(
            "test_Equal_graph",
            vec![f32_input("A", &[1, 2]), f32_input("B", &[1, 2])],
            vec![bool_output("C", &[1, 2])],
            vec![node("Equal", "test_Equal", &["A", "B"], &["C"], &[])],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_19() {
    assert_op_matches_ort(build_fixture_opset_19(), ExpectConvertOp::Success, 19);
}

fn build_fixture_opset_19_float16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        19,
        graph(
            "test_Equal_graph",
            vec![f16_input("A", &[1, 2]), f16_input("B", &[1, 2])],
            vec![bool_output("C", &[1, 2])],
            vec![node("Equal", "test_Equal", &["A", "B"], &["C"], &[])],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_19_float16() {
    assert_op_matches_ort(
        build_fixture_opset_19_float16(),
        ExpectConvertOp::Success,
        19,
    );
}

fn build_fixture_opset_13_bfloat16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        13,
        graph(
            "test_Equal_graph",
            vec![bf16_input("A", &[1, 2]), bf16_input("B", &[1, 2])],
            vec![bool_output("C", &[1, 2])],
            vec![node("Equal", "test_Equal", &["A", "B"], &["C"], &[])],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_13_bfloat16() {
    assert_op_matches_ort(
        build_fixture_opset_13_bfloat16(),
        ExpectConvertOp::ConversionError,
        13,
    );
}
