/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Col2Im` operator conversion tests (fixture opsets: 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_Col2Im_graph",
            vec![
            ],
            vec![
                f32_output("output", &[1, 1, 5, 5]),
            ],
            vec![
                node(
                    "Col2Im",
                    "test_Col2Im",
                    &["input", "image_shape", "block_shape"],
                    &["output"],
                    &[],
                ),
            ],
            vec![
                f32_init("input", &[1, 5, 5], &[1.0, 6.0, 11.0, 16.0, 21.0, 2.0, 7.0, 12.0, 17.0, 22.0, 3.0, 8.0, 13.0, 18.0, 23.0, 4.0, 9.0, 14.0, 19.0, 24.0, 5.0, 0.0, 15.0, 20.0, 25.0]),
                i64_init("image_shape", &[2], &[5, 5]),
                i64_init("block_shape", &[2], &[1, 5]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::UnsupportedOp, 26);
}
