/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Col2Im` operator conversion test (fixture opset 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

// Fixture builder failed at codegen: Node(test_Col2Im) with schema(::Col2Im:18) has input size 2 not in range [min=3, max=3]. ==> Context: Bad node spec for node. Name: test_Col2Im OpType: Col2Im
#[test]
#[ignore = "fixture builder failed at codegen: Node test_Col2Im with schema ::Col2Im:18 has input size 2 not in range min 3 max 3 . Context: Bad node spec for node. Na"]
fn opset26() {}
