/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `ConvTranspose` operator conversion tests (fixture opsets: 22, 22, 22).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_22() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        22,
        graph(
            "test_ConvTranspose_graph",
            vec![f32_input("X", &[1, 1, 4, 4]), f32_input("W", &[1, 1, 3, 3])],
            vec![f32_output("Y", &[1, 1, 4, 4])],
            vec![node(
                "ConvTranspose",
                "test_ConvTranspose",
                &["X", "W"],
                &["Y"],
                &[attr_int("group", 1), attr_string("auto_pad", "NOTSET")],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_22() {
    assert_op_matches_ort(build_fixture_opset_22(), ExpectConvertOp::Success, 22);
}

fn build_fixture_opset_22_float16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        22,
        graph(
            "test_ConvTranspose_graph",
            vec![f16_input("X", &[1, 1, 4, 4]), f16_input("W", &[1, 1, 3, 3])],
            vec![f16_output("Y", &[1, 1, 4, 4])],
            vec![node(
                "ConvTranspose",
                "test_ConvTranspose",
                &["X", "W"],
                &["Y"],
                &[attr_int("group", 1), attr_string("auto_pad", "NOTSET")],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_22_float16() {
    assert_op_matches_ort(
        build_fixture_opset_22_float16(),
        ExpectConvertOp::Success,
        22,
    );
}

fn build_fixture_opset_22_bfloat16() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        22,
        graph(
            "test_ConvTranspose_graph",
            vec![
                bf16_input("X", &[1, 1, 4, 4]),
                bf16_input("W", &[1, 1, 3, 3]),
            ],
            vec![bf16_output("Y", &[1, 1, 4, 4])],
            vec![node(
                "ConvTranspose",
                "test_ConvTranspose",
                &["X", "W"],
                &["Y"],
                &[attr_int("group", 1), attr_string("auto_pad", "NOTSET")],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_22_bfloat16() {
    assert_op_matches_ort(
        build_fixture_opset_22_bfloat16(),
        ExpectConvertOp::ConversionError,
        22,
    );
}
