/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `ConvInteger` operator conversion tests (fixture opsets: 10).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_10() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        10,
        graph(
            "test_ConvInteger_graph",
            vec![],
            vec![i32_output("y", &[1, 1, 4, 4])],
            vec![node(
                "ConvInteger",
                "test",
                &["x", "w", "x_zero_point", "w_zero_point"],
                &["y"],
                &[],
            )],
            vec![
                u8_init(
                    "x",
                    &[1, 1, 4, 4],
                    &[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
                ),
                u8_init("w", &[1, 1, 1, 1], &[1]),
                u8_init("x_zero_point", &[], &[0]),
                u8_init("w_zero_point", &[], &[0]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_10() {
    assert_op_matches_ort(build_fixture_opset_10(), ExpectConvertOp::UnsupportedOp, 10);
}
