/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Conv` operator conversion tests (fixture opsets: 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_Conv_graph",
            vec![f32_input("X", &[1, 1, 4, 4]), f32_input("W", &[1, 1, 3, 3])],
            vec![f32_output("Y", &[1, 1, 4, 4])],
            vec![node(
                "Conv",
                "test_Conv",
                &["X", "W"],
                &["Y"],
                &[attr_int("group", 1), attr_string("auto_pad", "NOTSET")],
            )],
            vec![],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::Success, 26);
}
