/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `QLinearConv` operator conversion tests (fixture opsets: 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_QLinearConv_graph",
            vec![
            ],
            vec![
                u8_output("y", &[1, 1, 4, 4]),
            ],
            vec![
                node(
                    "QLinearConv",
                    "test",
                    &["x", "x_scale", "x_zero_point", "w", "w_scale", "w_zero_point", "y_scale", "y_zero_point"],
                    &["y"],
                    &[],
                ),
            ],
            vec![
                u8_init("x", &[1, 1, 4, 4], &[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]),
                f32_init("x_scale", &[], &[0.5]),
                u8_init("x_zero_point", &[], &[0]),
                u8_init("w", &[1, 1, 1, 1], &[1]),
                f32_init("w_scale", &[], &[0.25]),
                u8_init("w_zero_point", &[], &[0]),
                f32_init("y_scale", &[], &[0.125]),
                u8_init("y_zero_point", &[], &[0]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::UnsupportedOp, 26);
}
