/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `If` operator conversion tests (fixture opsets: 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_If_graph",
            vec![
            ],
            vec![
                f32_output("out", &[1, 2]),
            ],
            vec![
                node(
                    "If",
                    "test_If",
                    &["cond"],
                    &["out"],
                    &[
                        attr_graph("else_branch", graph(
                                "else",
                                vec![
                                ],
                                vec![
                                    f32_output("else_out", &[1, 2]),
                                ],
                                vec![
                                    node(
                                        "Constant",
                                        "",
                                        &[],
                                        &["else_out"],
                                        &[
                                            attr_tensor("value", f32_init("v", &[], &[2.0])),
                                        ],
                                    ),
                                ],
                                vec![
                                ],
                            )),
                        attr_graph("then_branch", graph(
                                "then",
                                vec![
                                ],
                                vec![
                                    f32_output("then_out", &[1, 2]),
                                ],
                                vec![
                                    node(
                                        "Constant",
                                        "",
                                        &[],
                                        &["then_out"],
                                        &[
                                            attr_tensor("value", f32_init("v", &[], &[1.0])),
                                        ],
                                    ),
                                ],
                                vec![
                                ],
                            )),
                    ],
                ),
            ],
            vec![
                bool_init("cond", &[], &[true]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::UnsupportedOp, 26);
}
