/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Loop` operator conversion test (fixture opset 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

// Fixture builder failed at codegen: Node with schema(::Identity:25) has input size 0 not in range [min=1, max=1]. ==> Context: Bad node spec for node. Name: test_Loop OpType: Loop
#[test]
#[ignore = "fixture builder failed at codegen: Node with schema ::Identity:25 has input size 0 not in range min 1 max 1 . Context: Bad node spec for node. Name: test_L"]
fn opset26() {}
