/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Loop` operator conversion tests (fixture opsets: 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_Loop_graph",
            vec![
            ],
            vec![
                i64_output("v_final", &[]),
            ],
            vec![
                node(
                    "Loop",
                    "test_Loop",
                    &["M", "cond", "v_init"],
                    &["v_final"],
                    &[
                        attr_graph("body", graph(
                                "body",
                                vec![
                                    i64_input("iteration_num", &[]),
                                    bool_input("cond_in", &[]),
                                    i64_input("v_in", &[]),
                                ],
                                vec![
                                    bool_output("cond_out", &[]),
                                    i64_output("v_out", &[]),
                                ],
                                vec![
                                    node(
                                        "Constant",
                                        "set_false",
                                        &[],
                                        &["cond_out"],
                                        &[
                                            attr_tensor("value", bool_init("false", &[], &[false])),
                                        ],
                                    ),
                                    node(
                                        "Identity",
                                        "pass",
                                        &["v_in"],
                                        &["v_out"],
                                        &[],
                                    ),
                                ],
                                vec![
                                ],
                            )),
                    ],
                ),
            ],
            vec![
                i64_init("M", &[], &[1]),
                bool_init("cond", &[], &[true]),
                i64_init("v_init", &[], &[0]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::UnsupportedOp, 26);
}
