/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `Scan` operator conversion tests (fixture opsets: 26).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_26() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        26,
        graph(
            "test_Scan_graph",
            vec![],
            vec![f32_output("out", &[1, 1, 2])],
            vec![node(
                "Scan",
                "test_Scan",
                &["init", "scan"],
                &["out"],
                &[
                    attr_graph(
                        "body",
                        graph(
                            "body",
                            vec![f32_input("scan_in", &[1, 2])],
                            vec![f32_output("scan_out", &[1, 2])],
                            vec![node("Identity", "id", &["scan_in"], &["scan_out"], &[])],
                            vec![],
                        ),
                    ),
                    attr_int("num_scan_inputs", 1),
                ],
            )],
            vec![
                f32_init("init", &[1, 2], &[0.0, 0.0]),
                f32_init("scan", &[1, 1, 2], &[0.0, 0.0]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_26() {
    assert_op_matches_ort(build_fixture_opset_26(), ExpectConvertOp::UnsupportedOp, 26);
}
